/* automatically generated by rust-bindgen 0.72.1 */

#![allow(
    non_camel_case_types,
    unsafe_op_in_unsafe_fn,
    clippy::missing_safety_doc,
    clippy::too_many_arguments
)]

use super::*;

pub struct cbf_bridge {
    __library: ::libloading::Library,
    pub cbf_bridge_convert_nsevent: unsafe extern "C" fn(
        nsevent: *mut ::std::os::raw::c_void,
        tab_id: u64,
        out_event: *mut CbfKeyEvent,
    ),
    pub cbf_bridge_free_converted_key_event: unsafe extern "C" fn(event: *mut CbfKeyEvent),
    pub cbf_bridge_convert_nsevent_to_mouse_event: unsafe extern "C" fn(
        nsevent: *mut ::std::os::raw::c_void,
        nsview: *mut ::std::os::raw::c_void,
        tab_id: u64,
        pointer_type: u8,
        unaccelerated_movement: bool,
        out_event: *mut CbfMouseEvent,
    ),
    pub cbf_bridge_convert_nsevent_to_mouse_wheel_event: unsafe extern "C" fn(
        nsevent: *mut ::std::os::raw::c_void,
        nsview: *mut ::std::os::raw::c_void,
        tab_id: u64,
        out_event: *mut CbfMouseWheelEvent,
    ),
    pub cbf_bridge_convert_nspasteboard_to_drag_data:
        unsafe extern "C" fn(nspasteboard: *mut ::std::os::raw::c_void, out_data: *mut CbfDragData),
    pub cbf_bridge_free_converted_drag_data: unsafe extern "C" fn(data: *mut CbfDragData),
    pub cbf_bridge_client_wait_for_event: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        timeout_ms: i64,
    ) -> CbfBridgeEventWaitStatus,
    pub cbf_bridge_client_send_external_drag_enter: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        event: *const CbfExternalDragEnter,
    ) -> bool,
    pub cbf_bridge_client_send_external_drag_update: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        event: *const CbfExternalDragUpdate,
    ) -> bool,
    pub cbf_bridge_client_send_external_drag_leave:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, tab_id: u64) -> bool,
    pub cbf_bridge_client_send_external_drag_drop: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        event: *const CbfExternalDragDrop,
    ) -> bool,
    pub cbf_bridge_client_execute_edit_action:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, tab_id: u64, action: u8) -> bool,
    pub cbf_bridge_client_find_in_page: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        request_id: u64,
        query: *const ::std::os::raw::c_char,
        forward: bool,
        match_case: bool,
        new_session: bool,
        find_match: bool,
    ) -> bool,
    pub cbf_bridge_client_stop_finding:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, tab_id: u64, action: u8) -> bool,
    pub cbf_bridge_client_execute_extension_popup_edit_action:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, popup_id: u64, action: u8) -> bool,
    pub cbf_bridge_client_execute_context_menu_command: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        menu_id: u64,
        command_id: i32,
        event_flags: i32,
    ) -> bool,
    pub cbf_bridge_client_dismiss_context_menu:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, menu_id: u64) -> bool,
    pub cbf_bridge_client_accept_choice_menu_selection: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
        indices: *const CbfChoiceMenuSelectedIndices,
    ) -> bool,
    pub cbf_bridge_client_dismiss_choice_menu:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, request_id: u64) -> bool,
    pub cbf_bridge_client_confirm_beforeunload: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        request_id: u64,
        proceed: bool,
    ) -> bool,
    pub cbf_bridge_client_respond_javascript_dialog: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        request_id: u64,
        accept: bool,
        prompt_text: *const ::std::os::raw::c_char,
    ) -> bool,
    pub cbf_bridge_client_respond_extension_popup_javascript_dialog: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        request_id: u64,
        accept: bool,
        prompt_text: *const ::std::os::raw::c_char,
    )
        -> bool,
    pub cbf_bridge_client_navigate: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        url: *const ::std::os::raw::c_char,
    ) -> bool,
    pub cbf_bridge_client_go_back:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, tab_id: u64) -> bool,
    pub cbf_bridge_client_go_forward:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, tab_id: u64) -> bool,
    pub cbf_bridge_client_reload: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        ignore_cache: bool,
    ) -> bool,
    pub cbf_bridge_client_print_preview:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, tab_id: u64) -> bool,
    pub cbf_bridge_client_activate_extension_action: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        extension_id: *const ::std::os::raw::c_char,
    ) -> bool,
    pub cbf_bridge_client_open_dev_tools:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, tab_id: u64) -> bool,
    pub cbf_bridge_client_inspect_element: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        x: i32,
        y: i32,
    ) -> bool,
    pub cbf_bridge_client_set_tab_focus: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        focused: bool,
    ) -> bool,
    pub cbf_bridge_client_set_tab_visibility: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        visibility: u8,
    ) -> bool,
    pub cbf_bridge_client_enable_tab_ipc: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        allowed_origins: *const CbfCommandList,
    ) -> bool,
    pub cbf_bridge_client_disable_tab_ipc:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, tab_id: u64) -> bool,
    pub cbf_bridge_client_post_tab_ipc_message: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        channel: *const ::std::os::raw::c_char,
        message_type: u8,
        request_id: u64,
        payload_kind: u8,
        payload_text: *const ::std::os::raw::c_char,
        payload_binary: *const u8,
        payload_binary_len: u32,
        content_type: *const ::std::os::raw::c_char,
        error_code: u8,
    ) -> bool,
    pub cbf_bridge_client_set_tab_background_policy: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        transparent: bool,
    ) -> bool,
    pub cbf_bridge_client_set_extension_popup_background_policy: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        transparent: bool,
    ) -> bool,
    pub cbf_bridge_client_get_tab_dom_html: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        request_id: u64,
    ) -> bool,
    pub cbf_bridge_client_list_extensions: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        profile_id: *const ::std::os::raw::c_char,
        out_list: *mut CbfExtensionInfoList,
    ) -> bool,
    pub cbf_bridge_extension_list_free: unsafe extern "C" fn(list: *mut CbfExtensionInfoList),
    pub cbf_bridge_client_open_default_prompt_ui: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        profile_id: *const ::std::os::raw::c_char,
        request_id: u64,
    ) -> bool,
    pub cbf_bridge_client_register_custom_scheme_handler: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        scheme: *const ::std::os::raw::c_char,
        host: *const ::std::os::raw::c_char,
    ) -> bool,
    pub cbf_bridge_client_respond_custom_scheme_request: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
        result: u8,
        mime_type: *const ::std::os::raw::c_char,
        content_security_policy: *const ::std::os::raw::c_char,
        access_control_allow_origin: *const ::std::os::raw::c_char,
        body: *const u8,
        body_len: u32,
    ) -> bool,
    pub cbf_bridge_client_respond_prompt_ui: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        profile_id: *const ::std::os::raw::c_char,
        request_id: u64,
        prompt_ui_kind: u8,
        proceed: bool,
        report_abuse: bool,
        destination_path: *const ::std::os::raw::c_char,
    ) -> bool,
    pub cbf_bridge_client_respond_prompt_ui_for_tab: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        request_id: u64,
        prompt_ui_kind: u8,
        proceed: bool,
        report_abuse: bool,
        destination_path: *const ::std::os::raw::c_char,
    ) -> bool,
    pub cbf_bridge_client_pause_download:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, download_id: u64) -> bool,
    pub cbf_bridge_client_resume_download:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, download_id: u64) -> bool,
    pub cbf_bridge_client_cancel_download:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, download_id: u64) -> bool,
    pub cbf_bridge_client_close_prompt_ui: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        profile_id: *const ::std::os::raw::c_char,
        prompt_ui_id: u64,
    ) -> bool,
    pub cbf_bridge_client_respond_tab_open: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
        response_kind: u8,
        target_tab_id: u64,
        activate: bool,
    ) -> bool,
    pub cbf_bridge_set_base_bundle_id:
        unsafe extern "C" fn(bundle_id: *const ::std::os::raw::c_char),
    pub cbf_bridge_client_create: unsafe extern "C" fn() -> *mut CbfBridgeClientHandle,
    pub cbf_bridge_client_destroy: unsafe extern "C" fn(client: *mut CbfBridgeClientHandle),
    pub cbf_bridge_init: unsafe extern "C" fn(),
    pub cbf_bridge_prepare_channel: unsafe extern "C" fn(
        out_switch_arg: *mut ::std::os::raw::c_char,
        out_arg_len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
    pub cbf_bridge_pass_child_pid: unsafe extern "C" fn(child_pid: i64),
    pub cbf_bridge_client_connect_inherited:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle) -> bool,
    pub cbf_bridge_client_authenticate: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        token: *const ::std::os::raw::c_char,
    ) -> bool,
    pub cbf_bridge_client_poll_event: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        out_event: *mut CbfBridgeEvent,
    ) -> bool,
    pub cbf_bridge_event_free: unsafe extern "C" fn(event: *mut CbfBridgeEvent),
    pub cbf_bridge_client_get_profiles: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        out_list: *mut CbfProfileList,
    ) -> bool,
    pub cbf_bridge_profile_list_free: unsafe extern "C" fn(list: *mut CbfProfileList),
    pub cbf_bridge_client_create_tab: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
        initial_url: *const ::std::os::raw::c_char,
        profile_id: *const ::std::os::raw::c_char,
    ) -> bool,
    pub cbf_bridge_client_request_close_tab:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, tab_id: u64) -> bool,
    pub cbf_bridge_client_set_tab_size: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        width: u32,
        height: u32,
    ) -> bool,
    pub cbf_bridge_client_send_key_event: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        event: *const CbfKeyEvent,
        commands: *const CbfCommandList,
    ) -> bool,
    pub cbf_bridge_client_send_mouse_event: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        event: *const CbfMouseEvent,
    ) -> bool,
    pub cbf_bridge_client_send_mouse_wheel_event: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        event: *const CbfMouseWheelEvent,
    ) -> bool,
    pub cbf_bridge_client_send_drag_update: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        update: *const CbfDragUpdate,
    ) -> bool,
    pub cbf_bridge_client_send_drag_drop:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, drop: *const CbfDragDrop) -> bool,
    pub cbf_bridge_client_send_drag_cancel: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        session_id: u64,
        tab_id: u64,
    ) -> bool,
    pub cbf_bridge_client_send_mac_event: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        nsevent: *mut ::std::os::raw::c_void,
    ) -> bool,
    pub cbf_bridge_client_set_composition: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        composition: *const CbfImeComposition,
    ) -> bool,
    pub cbf_bridge_client_commit_text: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        commit: *const CbfImeCommitText,
    ) -> bool,
    pub cbf_bridge_client_finish_composing_text:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, tab_id: u64, behavior: u8) -> bool,
    pub cbf_bridge_client_set_extension_popup_size: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        width: u32,
        height: u32,
    ) -> bool,
    pub cbf_bridge_client_set_extension_popup_focus: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        focused: bool,
    ) -> bool,
    pub cbf_bridge_client_send_extension_popup_key_event: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        event: *const CbfKeyEvent,
        commands: *const CbfCommandList,
    ) -> bool,
    pub cbf_bridge_client_send_extension_popup_mouse_event: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        event: *const CbfMouseEvent,
    ) -> bool,
    pub cbf_bridge_client_send_extension_popup_mouse_wheel_event: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        event: *const CbfMouseWheelEvent,
    ) -> bool,
    pub cbf_bridge_client_set_extension_popup_composition: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        composition: *const CbfImeComposition,
    ) -> bool,
    pub cbf_bridge_client_commit_extension_popup_text: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        commit: *const CbfImeCommitText,
    ) -> bool,
    pub cbf_bridge_client_finish_extension_popup_composing_text: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        behavior: u8,
    ) -> bool,
    pub cbf_bridge_client_close_extension_popup:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, popup_id: u64) -> bool,
    pub cbf_bridge_client_shutdown: unsafe extern "C" fn(client: *mut CbfBridgeClientHandle),
    pub cbf_bridge_client_request_shutdown:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle, request_id: u64) -> bool,
    pub cbf_bridge_client_confirm_shutdown: unsafe extern "C" fn(
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
        proceed: bool,
    ) -> bool,
    pub cbf_bridge_client_force_shutdown:
        unsafe extern "C" fn(client: *mut CbfBridgeClientHandle) -> bool,
}
impl cbf_bridge {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let library = ::libloading::Library::new(path)?;
        Self::from_library(library)
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let cbf_bridge_convert_nsevent = __library
            .get(b"cbf_bridge_convert_nsevent\0")
            .map(|sym| *sym)?;
        let cbf_bridge_free_converted_key_event = __library
            .get(b"cbf_bridge_free_converted_key_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_convert_nsevent_to_mouse_event = __library
            .get(b"cbf_bridge_convert_nsevent_to_mouse_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_convert_nsevent_to_mouse_wheel_event = __library
            .get(b"cbf_bridge_convert_nsevent_to_mouse_wheel_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_convert_nspasteboard_to_drag_data = __library
            .get(b"cbf_bridge_convert_nspasteboard_to_drag_data\0")
            .map(|sym| *sym)?;
        let cbf_bridge_free_converted_drag_data = __library
            .get(b"cbf_bridge_free_converted_drag_data\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_wait_for_event = __library
            .get(b"cbf_bridge_client_wait_for_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_external_drag_enter = __library
            .get(b"cbf_bridge_client_send_external_drag_enter\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_external_drag_update = __library
            .get(b"cbf_bridge_client_send_external_drag_update\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_external_drag_leave = __library
            .get(b"cbf_bridge_client_send_external_drag_leave\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_external_drag_drop = __library
            .get(b"cbf_bridge_client_send_external_drag_drop\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_execute_edit_action = __library
            .get(b"cbf_bridge_client_execute_edit_action\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_find_in_page = __library
            .get(b"cbf_bridge_client_find_in_page\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_stop_finding = __library
            .get(b"cbf_bridge_client_stop_finding\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_execute_extension_popup_edit_action = __library
            .get(b"cbf_bridge_client_execute_extension_popup_edit_action\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_execute_context_menu_command = __library
            .get(b"cbf_bridge_client_execute_context_menu_command\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_dismiss_context_menu = __library
            .get(b"cbf_bridge_client_dismiss_context_menu\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_accept_choice_menu_selection = __library
            .get(b"cbf_bridge_client_accept_choice_menu_selection\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_dismiss_choice_menu = __library
            .get(b"cbf_bridge_client_dismiss_choice_menu\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_confirm_beforeunload = __library
            .get(b"cbf_bridge_client_confirm_beforeunload\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_respond_javascript_dialog = __library
            .get(b"cbf_bridge_client_respond_javascript_dialog\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_respond_extension_popup_javascript_dialog = __library
            .get(b"cbf_bridge_client_respond_extension_popup_javascript_dialog\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_navigate = __library
            .get(b"cbf_bridge_client_navigate\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_go_back = __library
            .get(b"cbf_bridge_client_go_back\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_go_forward = __library
            .get(b"cbf_bridge_client_go_forward\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_reload = __library
            .get(b"cbf_bridge_client_reload\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_print_preview = __library
            .get(b"cbf_bridge_client_print_preview\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_activate_extension_action = __library
            .get(b"cbf_bridge_client_activate_extension_action\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_open_dev_tools = __library
            .get(b"cbf_bridge_client_open_dev_tools\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_inspect_element = __library
            .get(b"cbf_bridge_client_inspect_element\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_set_tab_focus = __library
            .get(b"cbf_bridge_client_set_tab_focus\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_set_tab_visibility = __library
            .get(b"cbf_bridge_client_set_tab_visibility\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_enable_tab_ipc = __library
            .get(b"cbf_bridge_client_enable_tab_ipc\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_disable_tab_ipc = __library
            .get(b"cbf_bridge_client_disable_tab_ipc\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_post_tab_ipc_message = __library
            .get(b"cbf_bridge_client_post_tab_ipc_message\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_set_tab_background_policy = __library
            .get(b"cbf_bridge_client_set_tab_background_policy\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_set_extension_popup_background_policy = __library
            .get(b"cbf_bridge_client_set_extension_popup_background_policy\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_get_tab_dom_html = __library
            .get(b"cbf_bridge_client_get_tab_dom_html\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_list_extensions = __library
            .get(b"cbf_bridge_client_list_extensions\0")
            .map(|sym| *sym)?;
        let cbf_bridge_extension_list_free = __library
            .get(b"cbf_bridge_extension_list_free\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_open_default_prompt_ui = __library
            .get(b"cbf_bridge_client_open_default_prompt_ui\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_register_custom_scheme_handler = __library
            .get(b"cbf_bridge_client_register_custom_scheme_handler\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_respond_custom_scheme_request = __library
            .get(b"cbf_bridge_client_respond_custom_scheme_request\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_respond_prompt_ui = __library
            .get(b"cbf_bridge_client_respond_prompt_ui\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_respond_prompt_ui_for_tab = __library
            .get(b"cbf_bridge_client_respond_prompt_ui_for_tab\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_pause_download = __library
            .get(b"cbf_bridge_client_pause_download\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_resume_download = __library
            .get(b"cbf_bridge_client_resume_download\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_cancel_download = __library
            .get(b"cbf_bridge_client_cancel_download\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_close_prompt_ui = __library
            .get(b"cbf_bridge_client_close_prompt_ui\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_respond_tab_open = __library
            .get(b"cbf_bridge_client_respond_tab_open\0")
            .map(|sym| *sym)?;
        let cbf_bridge_set_base_bundle_id = __library
            .get(b"cbf_bridge_set_base_bundle_id\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_create = __library
            .get(b"cbf_bridge_client_create\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_destroy = __library
            .get(b"cbf_bridge_client_destroy\0")
            .map(|sym| *sym)?;
        let cbf_bridge_init = __library.get(b"cbf_bridge_init\0").map(|sym| *sym)?;
        let cbf_bridge_prepare_channel = __library
            .get(b"cbf_bridge_prepare_channel\0")
            .map(|sym| *sym)?;
        let cbf_bridge_pass_child_pid = __library
            .get(b"cbf_bridge_pass_child_pid\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_connect_inherited = __library
            .get(b"cbf_bridge_client_connect_inherited\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_authenticate = __library
            .get(b"cbf_bridge_client_authenticate\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_poll_event = __library
            .get(b"cbf_bridge_client_poll_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_event_free = __library.get(b"cbf_bridge_event_free\0").map(|sym| *sym)?;
        let cbf_bridge_client_get_profiles = __library
            .get(b"cbf_bridge_client_get_profiles\0")
            .map(|sym| *sym)?;
        let cbf_bridge_profile_list_free = __library
            .get(b"cbf_bridge_profile_list_free\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_create_tab = __library
            .get(b"cbf_bridge_client_create_tab\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_request_close_tab = __library
            .get(b"cbf_bridge_client_request_close_tab\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_set_tab_size = __library
            .get(b"cbf_bridge_client_set_tab_size\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_key_event = __library
            .get(b"cbf_bridge_client_send_key_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_mouse_event = __library
            .get(b"cbf_bridge_client_send_mouse_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_mouse_wheel_event = __library
            .get(b"cbf_bridge_client_send_mouse_wheel_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_drag_update = __library
            .get(b"cbf_bridge_client_send_drag_update\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_drag_drop = __library
            .get(b"cbf_bridge_client_send_drag_drop\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_drag_cancel = __library
            .get(b"cbf_bridge_client_send_drag_cancel\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_mac_event = __library
            .get(b"cbf_bridge_client_send_mac_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_set_composition = __library
            .get(b"cbf_bridge_client_set_composition\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_commit_text = __library
            .get(b"cbf_bridge_client_commit_text\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_finish_composing_text = __library
            .get(b"cbf_bridge_client_finish_composing_text\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_set_extension_popup_size = __library
            .get(b"cbf_bridge_client_set_extension_popup_size\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_set_extension_popup_focus = __library
            .get(b"cbf_bridge_client_set_extension_popup_focus\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_extension_popup_key_event = __library
            .get(b"cbf_bridge_client_send_extension_popup_key_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_extension_popup_mouse_event = __library
            .get(b"cbf_bridge_client_send_extension_popup_mouse_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_send_extension_popup_mouse_wheel_event = __library
            .get(b"cbf_bridge_client_send_extension_popup_mouse_wheel_event\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_set_extension_popup_composition = __library
            .get(b"cbf_bridge_client_set_extension_popup_composition\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_commit_extension_popup_text = __library
            .get(b"cbf_bridge_client_commit_extension_popup_text\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_finish_extension_popup_composing_text = __library
            .get(b"cbf_bridge_client_finish_extension_popup_composing_text\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_close_extension_popup = __library
            .get(b"cbf_bridge_client_close_extension_popup\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_shutdown = __library
            .get(b"cbf_bridge_client_shutdown\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_request_shutdown = __library
            .get(b"cbf_bridge_client_request_shutdown\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_confirm_shutdown = __library
            .get(b"cbf_bridge_client_confirm_shutdown\0")
            .map(|sym| *sym)?;
        let cbf_bridge_client_force_shutdown = __library
            .get(b"cbf_bridge_client_force_shutdown\0")
            .map(|sym| *sym)?;
        Ok(cbf_bridge {
            __library,
            cbf_bridge_convert_nsevent,
            cbf_bridge_free_converted_key_event,
            cbf_bridge_convert_nsevent_to_mouse_event,
            cbf_bridge_convert_nsevent_to_mouse_wheel_event,
            cbf_bridge_convert_nspasteboard_to_drag_data,
            cbf_bridge_free_converted_drag_data,
            cbf_bridge_client_wait_for_event,
            cbf_bridge_client_send_external_drag_enter,
            cbf_bridge_client_send_external_drag_update,
            cbf_bridge_client_send_external_drag_leave,
            cbf_bridge_client_send_external_drag_drop,
            cbf_bridge_client_execute_edit_action,
            cbf_bridge_client_find_in_page,
            cbf_bridge_client_stop_finding,
            cbf_bridge_client_execute_extension_popup_edit_action,
            cbf_bridge_client_execute_context_menu_command,
            cbf_bridge_client_dismiss_context_menu,
            cbf_bridge_client_accept_choice_menu_selection,
            cbf_bridge_client_dismiss_choice_menu,
            cbf_bridge_client_confirm_beforeunload,
            cbf_bridge_client_respond_javascript_dialog,
            cbf_bridge_client_respond_extension_popup_javascript_dialog,
            cbf_bridge_client_navigate,
            cbf_bridge_client_go_back,
            cbf_bridge_client_go_forward,
            cbf_bridge_client_reload,
            cbf_bridge_client_print_preview,
            cbf_bridge_client_activate_extension_action,
            cbf_bridge_client_open_dev_tools,
            cbf_bridge_client_inspect_element,
            cbf_bridge_client_set_tab_focus,
            cbf_bridge_client_set_tab_visibility,
            cbf_bridge_client_enable_tab_ipc,
            cbf_bridge_client_disable_tab_ipc,
            cbf_bridge_client_post_tab_ipc_message,
            cbf_bridge_client_set_tab_background_policy,
            cbf_bridge_client_set_extension_popup_background_policy,
            cbf_bridge_client_get_tab_dom_html,
            cbf_bridge_client_list_extensions,
            cbf_bridge_extension_list_free,
            cbf_bridge_client_open_default_prompt_ui,
            cbf_bridge_client_register_custom_scheme_handler,
            cbf_bridge_client_respond_custom_scheme_request,
            cbf_bridge_client_respond_prompt_ui,
            cbf_bridge_client_respond_prompt_ui_for_tab,
            cbf_bridge_client_pause_download,
            cbf_bridge_client_resume_download,
            cbf_bridge_client_cancel_download,
            cbf_bridge_client_close_prompt_ui,
            cbf_bridge_client_respond_tab_open,
            cbf_bridge_set_base_bundle_id,
            cbf_bridge_client_create,
            cbf_bridge_client_destroy,
            cbf_bridge_init,
            cbf_bridge_prepare_channel,
            cbf_bridge_pass_child_pid,
            cbf_bridge_client_connect_inherited,
            cbf_bridge_client_authenticate,
            cbf_bridge_client_poll_event,
            cbf_bridge_event_free,
            cbf_bridge_client_get_profiles,
            cbf_bridge_profile_list_free,
            cbf_bridge_client_create_tab,
            cbf_bridge_client_request_close_tab,
            cbf_bridge_client_set_tab_size,
            cbf_bridge_client_send_key_event,
            cbf_bridge_client_send_mouse_event,
            cbf_bridge_client_send_mouse_wheel_event,
            cbf_bridge_client_send_drag_update,
            cbf_bridge_client_send_drag_drop,
            cbf_bridge_client_send_drag_cancel,
            cbf_bridge_client_send_mac_event,
            cbf_bridge_client_set_composition,
            cbf_bridge_client_commit_text,
            cbf_bridge_client_finish_composing_text,
            cbf_bridge_client_set_extension_popup_size,
            cbf_bridge_client_set_extension_popup_focus,
            cbf_bridge_client_send_extension_popup_key_event,
            cbf_bridge_client_send_extension_popup_mouse_event,
            cbf_bridge_client_send_extension_popup_mouse_wheel_event,
            cbf_bridge_client_set_extension_popup_composition,
            cbf_bridge_client_commit_extension_popup_text,
            cbf_bridge_client_finish_extension_popup_composing_text,
            cbf_bridge_client_close_extension_popup,
            cbf_bridge_client_shutdown,
            cbf_bridge_client_request_shutdown,
            cbf_bridge_client_confirm_shutdown,
            cbf_bridge_client_force_shutdown,
        })
    }
    pub unsafe fn cbf_bridge_convert_nsevent(
        &self,
        nsevent: *mut ::std::os::raw::c_void,
        tab_id: u64,
        out_event: *mut CbfKeyEvent,
    ) {
        (self.cbf_bridge_convert_nsevent)(nsevent, tab_id, out_event)
    }
    pub unsafe fn cbf_bridge_free_converted_key_event(&self, event: *mut CbfKeyEvent) {
        (self.cbf_bridge_free_converted_key_event)(event)
    }
    pub unsafe fn cbf_bridge_convert_nsevent_to_mouse_event(
        &self,
        nsevent: *mut ::std::os::raw::c_void,
        nsview: *mut ::std::os::raw::c_void,
        tab_id: u64,
        pointer_type: u8,
        unaccelerated_movement: bool,
        out_event: *mut CbfMouseEvent,
    ) {
        (self.cbf_bridge_convert_nsevent_to_mouse_event)(
            nsevent,
            nsview,
            tab_id,
            pointer_type,
            unaccelerated_movement,
            out_event,
        )
    }
    pub unsafe fn cbf_bridge_convert_nsevent_to_mouse_wheel_event(
        &self,
        nsevent: *mut ::std::os::raw::c_void,
        nsview: *mut ::std::os::raw::c_void,
        tab_id: u64,
        out_event: *mut CbfMouseWheelEvent,
    ) {
        (self.cbf_bridge_convert_nsevent_to_mouse_wheel_event)(nsevent, nsview, tab_id, out_event)
    }
    pub unsafe fn cbf_bridge_convert_nspasteboard_to_drag_data(
        &self,
        nspasteboard: *mut ::std::os::raw::c_void,
        out_data: *mut CbfDragData,
    ) {
        (self.cbf_bridge_convert_nspasteboard_to_drag_data)(nspasteboard, out_data)
    }
    pub unsafe fn cbf_bridge_free_converted_drag_data(&self, data: *mut CbfDragData) {
        (self.cbf_bridge_free_converted_drag_data)(data)
    }
    pub unsafe fn cbf_bridge_client_wait_for_event(
        &self,
        client: *mut CbfBridgeClientHandle,
        timeout_ms: i64,
    ) -> CbfBridgeEventWaitStatus {
        (self.cbf_bridge_client_wait_for_event)(client, timeout_ms)
    }
    pub unsafe fn cbf_bridge_client_send_external_drag_enter(
        &self,
        client: *mut CbfBridgeClientHandle,
        event: *const CbfExternalDragEnter,
    ) -> bool {
        (self.cbf_bridge_client_send_external_drag_enter)(client, event)
    }
    pub unsafe fn cbf_bridge_client_send_external_drag_update(
        &self,
        client: *mut CbfBridgeClientHandle,
        event: *const CbfExternalDragUpdate,
    ) -> bool {
        (self.cbf_bridge_client_send_external_drag_update)(client, event)
    }
    pub unsafe fn cbf_bridge_client_send_external_drag_leave(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_send_external_drag_leave)(client, tab_id)
    }
    pub unsafe fn cbf_bridge_client_send_external_drag_drop(
        &self,
        client: *mut CbfBridgeClientHandle,
        event: *const CbfExternalDragDrop,
    ) -> bool {
        (self.cbf_bridge_client_send_external_drag_drop)(client, event)
    }
    pub unsafe fn cbf_bridge_client_execute_edit_action(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        action: u8,
    ) -> bool {
        (self.cbf_bridge_client_execute_edit_action)(client, tab_id, action)
    }
    pub unsafe fn cbf_bridge_client_find_in_page(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        request_id: u64,
        query: *const ::std::os::raw::c_char,
        forward: bool,
        match_case: bool,
        new_session: bool,
        find_match: bool,
    ) -> bool {
        (self.cbf_bridge_client_find_in_page)(
            client,
            tab_id,
            request_id,
            query,
            forward,
            match_case,
            new_session,
            find_match,
        )
    }
    pub unsafe fn cbf_bridge_client_stop_finding(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        action: u8,
    ) -> bool {
        (self.cbf_bridge_client_stop_finding)(client, tab_id, action)
    }
    pub unsafe fn cbf_bridge_client_execute_extension_popup_edit_action(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        action: u8,
    ) -> bool {
        (self.cbf_bridge_client_execute_extension_popup_edit_action)(client, popup_id, action)
    }
    pub unsafe fn cbf_bridge_client_execute_context_menu_command(
        &self,
        client: *mut CbfBridgeClientHandle,
        menu_id: u64,
        command_id: i32,
        event_flags: i32,
    ) -> bool {
        (self.cbf_bridge_client_execute_context_menu_command)(
            client,
            menu_id,
            command_id,
            event_flags,
        )
    }
    pub unsafe fn cbf_bridge_client_dismiss_context_menu(
        &self,
        client: *mut CbfBridgeClientHandle,
        menu_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_dismiss_context_menu)(client, menu_id)
    }
    pub unsafe fn cbf_bridge_client_accept_choice_menu_selection(
        &self,
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
        indices: *const CbfChoiceMenuSelectedIndices,
    ) -> bool {
        (self.cbf_bridge_client_accept_choice_menu_selection)(client, request_id, indices)
    }
    pub unsafe fn cbf_bridge_client_dismiss_choice_menu(
        &self,
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_dismiss_choice_menu)(client, request_id)
    }
    pub unsafe fn cbf_bridge_client_confirm_beforeunload(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        request_id: u64,
        proceed: bool,
    ) -> bool {
        (self.cbf_bridge_client_confirm_beforeunload)(client, tab_id, request_id, proceed)
    }
    pub unsafe fn cbf_bridge_client_respond_javascript_dialog(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        request_id: u64,
        accept: bool,
        prompt_text: *const ::std::os::raw::c_char,
    ) -> bool {
        (self.cbf_bridge_client_respond_javascript_dialog)(
            client,
            tab_id,
            request_id,
            accept,
            prompt_text,
        )
    }
    pub unsafe fn cbf_bridge_client_respond_extension_popup_javascript_dialog(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        request_id: u64,
        accept: bool,
        prompt_text: *const ::std::os::raw::c_char,
    ) -> bool {
        (self.cbf_bridge_client_respond_extension_popup_javascript_dialog)(
            client,
            popup_id,
            request_id,
            accept,
            prompt_text,
        )
    }
    pub unsafe fn cbf_bridge_client_navigate(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        url: *const ::std::os::raw::c_char,
    ) -> bool {
        (self.cbf_bridge_client_navigate)(client, tab_id, url)
    }
    pub unsafe fn cbf_bridge_client_go_back(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_go_back)(client, tab_id)
    }
    pub unsafe fn cbf_bridge_client_go_forward(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_go_forward)(client, tab_id)
    }
    pub unsafe fn cbf_bridge_client_reload(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        ignore_cache: bool,
    ) -> bool {
        (self.cbf_bridge_client_reload)(client, tab_id, ignore_cache)
    }
    pub unsafe fn cbf_bridge_client_print_preview(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_print_preview)(client, tab_id)
    }
    pub unsafe fn cbf_bridge_client_activate_extension_action(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        extension_id: *const ::std::os::raw::c_char,
    ) -> bool {
        (self.cbf_bridge_client_activate_extension_action)(client, tab_id, extension_id)
    }
    pub unsafe fn cbf_bridge_client_open_dev_tools(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_open_dev_tools)(client, tab_id)
    }
    pub unsafe fn cbf_bridge_client_inspect_element(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        x: i32,
        y: i32,
    ) -> bool {
        (self.cbf_bridge_client_inspect_element)(client, tab_id, x, y)
    }
    pub unsafe fn cbf_bridge_client_set_tab_focus(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        focused: bool,
    ) -> bool {
        (self.cbf_bridge_client_set_tab_focus)(client, tab_id, focused)
    }
    pub unsafe fn cbf_bridge_client_set_tab_visibility(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        visibility: u8,
    ) -> bool {
        (self.cbf_bridge_client_set_tab_visibility)(client, tab_id, visibility)
    }
    pub unsafe fn cbf_bridge_client_enable_tab_ipc(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        allowed_origins: *const CbfCommandList,
    ) -> bool {
        (self.cbf_bridge_client_enable_tab_ipc)(client, tab_id, allowed_origins)
    }
    pub unsafe fn cbf_bridge_client_disable_tab_ipc(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_disable_tab_ipc)(client, tab_id)
    }
    pub unsafe fn cbf_bridge_client_post_tab_ipc_message(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        channel: *const ::std::os::raw::c_char,
        message_type: u8,
        request_id: u64,
        payload_kind: u8,
        payload_text: *const ::std::os::raw::c_char,
        payload_binary: *const u8,
        payload_binary_len: u32,
        content_type: *const ::std::os::raw::c_char,
        error_code: u8,
    ) -> bool {
        (self.cbf_bridge_client_post_tab_ipc_message)(
            client,
            tab_id,
            channel,
            message_type,
            request_id,
            payload_kind,
            payload_text,
            payload_binary,
            payload_binary_len,
            content_type,
            error_code,
        )
    }
    pub unsafe fn cbf_bridge_client_set_tab_background_policy(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        transparent: bool,
    ) -> bool {
        (self.cbf_bridge_client_set_tab_background_policy)(client, tab_id, transparent)
    }
    pub unsafe fn cbf_bridge_client_set_extension_popup_background_policy(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        transparent: bool,
    ) -> bool {
        (self.cbf_bridge_client_set_extension_popup_background_policy)(
            client,
            popup_id,
            transparent,
        )
    }
    pub unsafe fn cbf_bridge_client_get_tab_dom_html(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        request_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_get_tab_dom_html)(client, tab_id, request_id)
    }
    pub unsafe fn cbf_bridge_client_list_extensions(
        &self,
        client: *mut CbfBridgeClientHandle,
        profile_id: *const ::std::os::raw::c_char,
        out_list: *mut CbfExtensionInfoList,
    ) -> bool {
        (self.cbf_bridge_client_list_extensions)(client, profile_id, out_list)
    }
    pub unsafe fn cbf_bridge_extension_list_free(&self, list: *mut CbfExtensionInfoList) {
        (self.cbf_bridge_extension_list_free)(list)
    }
    pub unsafe fn cbf_bridge_client_open_default_prompt_ui(
        &self,
        client: *mut CbfBridgeClientHandle,
        profile_id: *const ::std::os::raw::c_char,
        request_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_open_default_prompt_ui)(client, profile_id, request_id)
    }
    pub unsafe fn cbf_bridge_client_register_custom_scheme_handler(
        &self,
        client: *mut CbfBridgeClientHandle,
        scheme: *const ::std::os::raw::c_char,
        host: *const ::std::os::raw::c_char,
    ) -> bool {
        (self.cbf_bridge_client_register_custom_scheme_handler)(client, scheme, host)
    }
    pub unsafe fn cbf_bridge_client_respond_custom_scheme_request(
        &self,
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
        result: u8,
        mime_type: *const ::std::os::raw::c_char,
        content_security_policy: *const ::std::os::raw::c_char,
        access_control_allow_origin: *const ::std::os::raw::c_char,
        body: *const u8,
        body_len: u32,
    ) -> bool {
        (self.cbf_bridge_client_respond_custom_scheme_request)(
            client,
            request_id,
            result,
            mime_type,
            content_security_policy,
            access_control_allow_origin,
            body,
            body_len,
        )
    }
    pub unsafe fn cbf_bridge_client_respond_prompt_ui(
        &self,
        client: *mut CbfBridgeClientHandle,
        profile_id: *const ::std::os::raw::c_char,
        request_id: u64,
        prompt_ui_kind: u8,
        proceed: bool,
        report_abuse: bool,
        destination_path: *const ::std::os::raw::c_char,
    ) -> bool {
        (self.cbf_bridge_client_respond_prompt_ui)(
            client,
            profile_id,
            request_id,
            prompt_ui_kind,
            proceed,
            report_abuse,
            destination_path,
        )
    }
    pub unsafe fn cbf_bridge_client_respond_prompt_ui_for_tab(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        request_id: u64,
        prompt_ui_kind: u8,
        proceed: bool,
        report_abuse: bool,
        destination_path: *const ::std::os::raw::c_char,
    ) -> bool {
        (self.cbf_bridge_client_respond_prompt_ui_for_tab)(
            client,
            tab_id,
            request_id,
            prompt_ui_kind,
            proceed,
            report_abuse,
            destination_path,
        )
    }
    pub unsafe fn cbf_bridge_client_pause_download(
        &self,
        client: *mut CbfBridgeClientHandle,
        download_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_pause_download)(client, download_id)
    }
    pub unsafe fn cbf_bridge_client_resume_download(
        &self,
        client: *mut CbfBridgeClientHandle,
        download_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_resume_download)(client, download_id)
    }
    pub unsafe fn cbf_bridge_client_cancel_download(
        &self,
        client: *mut CbfBridgeClientHandle,
        download_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_cancel_download)(client, download_id)
    }
    pub unsafe fn cbf_bridge_client_close_prompt_ui(
        &self,
        client: *mut CbfBridgeClientHandle,
        profile_id: *const ::std::os::raw::c_char,
        prompt_ui_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_close_prompt_ui)(client, profile_id, prompt_ui_id)
    }
    pub unsafe fn cbf_bridge_client_respond_tab_open(
        &self,
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
        response_kind: u8,
        target_tab_id: u64,
        activate: bool,
    ) -> bool {
        (self.cbf_bridge_client_respond_tab_open)(
            client,
            request_id,
            response_kind,
            target_tab_id,
            activate,
        )
    }
    pub unsafe fn cbf_bridge_set_base_bundle_id(&self, bundle_id: *const ::std::os::raw::c_char) {
        (self.cbf_bridge_set_base_bundle_id)(bundle_id)
    }
    pub unsafe fn cbf_bridge_client_create(&self) -> *mut CbfBridgeClientHandle {
        (self.cbf_bridge_client_create)()
    }
    pub unsafe fn cbf_bridge_client_destroy(&self, client: *mut CbfBridgeClientHandle) {
        (self.cbf_bridge_client_destroy)(client)
    }
    pub unsafe fn cbf_bridge_init(&self) {
        (self.cbf_bridge_init)()
    }
    pub unsafe fn cbf_bridge_prepare_channel(
        &self,
        out_switch_arg: *mut ::std::os::raw::c_char,
        out_arg_len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int {
        (self.cbf_bridge_prepare_channel)(out_switch_arg, out_arg_len)
    }
    pub unsafe fn cbf_bridge_pass_child_pid(&self, child_pid: i64) {
        (self.cbf_bridge_pass_child_pid)(child_pid)
    }
    pub unsafe fn cbf_bridge_client_connect_inherited(
        &self,
        client: *mut CbfBridgeClientHandle,
    ) -> bool {
        (self.cbf_bridge_client_connect_inherited)(client)
    }
    pub unsafe fn cbf_bridge_client_authenticate(
        &self,
        client: *mut CbfBridgeClientHandle,
        token: *const ::std::os::raw::c_char,
    ) -> bool {
        (self.cbf_bridge_client_authenticate)(client, token)
    }
    pub unsafe fn cbf_bridge_client_poll_event(
        &self,
        client: *mut CbfBridgeClientHandle,
        out_event: *mut CbfBridgeEvent,
    ) -> bool {
        (self.cbf_bridge_client_poll_event)(client, out_event)
    }
    pub unsafe fn cbf_bridge_event_free(&self, event: *mut CbfBridgeEvent) {
        (self.cbf_bridge_event_free)(event)
    }
    pub unsafe fn cbf_bridge_client_get_profiles(
        &self,
        client: *mut CbfBridgeClientHandle,
        out_list: *mut CbfProfileList,
    ) -> bool {
        (self.cbf_bridge_client_get_profiles)(client, out_list)
    }
    pub unsafe fn cbf_bridge_profile_list_free(&self, list: *mut CbfProfileList) {
        (self.cbf_bridge_profile_list_free)(list)
    }
    pub unsafe fn cbf_bridge_client_create_tab(
        &self,
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
        initial_url: *const ::std::os::raw::c_char,
        profile_id: *const ::std::os::raw::c_char,
    ) -> bool {
        (self.cbf_bridge_client_create_tab)(client, request_id, initial_url, profile_id)
    }
    pub unsafe fn cbf_bridge_client_request_close_tab(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_request_close_tab)(client, tab_id)
    }
    pub unsafe fn cbf_bridge_client_set_tab_size(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        width: u32,
        height: u32,
    ) -> bool {
        (self.cbf_bridge_client_set_tab_size)(client, tab_id, width, height)
    }
    pub unsafe fn cbf_bridge_client_send_key_event(
        &self,
        client: *mut CbfBridgeClientHandle,
        event: *const CbfKeyEvent,
        commands: *const CbfCommandList,
    ) -> bool {
        (self.cbf_bridge_client_send_key_event)(client, event, commands)
    }
    pub unsafe fn cbf_bridge_client_send_mouse_event(
        &self,
        client: *mut CbfBridgeClientHandle,
        event: *const CbfMouseEvent,
    ) -> bool {
        (self.cbf_bridge_client_send_mouse_event)(client, event)
    }
    pub unsafe fn cbf_bridge_client_send_mouse_wheel_event(
        &self,
        client: *mut CbfBridgeClientHandle,
        event: *const CbfMouseWheelEvent,
    ) -> bool {
        (self.cbf_bridge_client_send_mouse_wheel_event)(client, event)
    }
    pub unsafe fn cbf_bridge_client_send_drag_update(
        &self,
        client: *mut CbfBridgeClientHandle,
        update: *const CbfDragUpdate,
    ) -> bool {
        (self.cbf_bridge_client_send_drag_update)(client, update)
    }
    pub unsafe fn cbf_bridge_client_send_drag_drop(
        &self,
        client: *mut CbfBridgeClientHandle,
        drop: *const CbfDragDrop,
    ) -> bool {
        (self.cbf_bridge_client_send_drag_drop)(client, drop)
    }
    pub unsafe fn cbf_bridge_client_send_drag_cancel(
        &self,
        client: *mut CbfBridgeClientHandle,
        session_id: u64,
        tab_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_send_drag_cancel)(client, session_id, tab_id)
    }
    pub unsafe fn cbf_bridge_client_send_mac_event(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        nsevent: *mut ::std::os::raw::c_void,
    ) -> bool {
        (self.cbf_bridge_client_send_mac_event)(client, tab_id, nsevent)
    }
    pub unsafe fn cbf_bridge_client_set_composition(
        &self,
        client: *mut CbfBridgeClientHandle,
        composition: *const CbfImeComposition,
    ) -> bool {
        (self.cbf_bridge_client_set_composition)(client, composition)
    }
    pub unsafe fn cbf_bridge_client_commit_text(
        &self,
        client: *mut CbfBridgeClientHandle,
        commit: *const CbfImeCommitText,
    ) -> bool {
        (self.cbf_bridge_client_commit_text)(client, commit)
    }
    pub unsafe fn cbf_bridge_client_finish_composing_text(
        &self,
        client: *mut CbfBridgeClientHandle,
        tab_id: u64,
        behavior: u8,
    ) -> bool {
        (self.cbf_bridge_client_finish_composing_text)(client, tab_id, behavior)
    }
    pub unsafe fn cbf_bridge_client_set_extension_popup_size(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        width: u32,
        height: u32,
    ) -> bool {
        (self.cbf_bridge_client_set_extension_popup_size)(client, popup_id, width, height)
    }
    pub unsafe fn cbf_bridge_client_set_extension_popup_focus(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        focused: bool,
    ) -> bool {
        (self.cbf_bridge_client_set_extension_popup_focus)(client, popup_id, focused)
    }
    pub unsafe fn cbf_bridge_client_send_extension_popup_key_event(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        event: *const CbfKeyEvent,
        commands: *const CbfCommandList,
    ) -> bool {
        (self.cbf_bridge_client_send_extension_popup_key_event)(client, popup_id, event, commands)
    }
    pub unsafe fn cbf_bridge_client_send_extension_popup_mouse_event(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        event: *const CbfMouseEvent,
    ) -> bool {
        (self.cbf_bridge_client_send_extension_popup_mouse_event)(client, popup_id, event)
    }
    pub unsafe fn cbf_bridge_client_send_extension_popup_mouse_wheel_event(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        event: *const CbfMouseWheelEvent,
    ) -> bool {
        (self.cbf_bridge_client_send_extension_popup_mouse_wheel_event)(client, popup_id, event)
    }
    pub unsafe fn cbf_bridge_client_set_extension_popup_composition(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        composition: *const CbfImeComposition,
    ) -> bool {
        (self.cbf_bridge_client_set_extension_popup_composition)(client, popup_id, composition)
    }
    pub unsafe fn cbf_bridge_client_commit_extension_popup_text(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        commit: *const CbfImeCommitText,
    ) -> bool {
        (self.cbf_bridge_client_commit_extension_popup_text)(client, popup_id, commit)
    }
    pub unsafe fn cbf_bridge_client_finish_extension_popup_composing_text(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
        behavior: u8,
    ) -> bool {
        (self.cbf_bridge_client_finish_extension_popup_composing_text)(client, popup_id, behavior)
    }
    pub unsafe fn cbf_bridge_client_close_extension_popup(
        &self,
        client: *mut CbfBridgeClientHandle,
        popup_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_close_extension_popup)(client, popup_id)
    }
    pub unsafe fn cbf_bridge_client_shutdown(&self, client: *mut CbfBridgeClientHandle) {
        (self.cbf_bridge_client_shutdown)(client)
    }
    pub unsafe fn cbf_bridge_client_request_shutdown(
        &self,
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
    ) -> bool {
        (self.cbf_bridge_client_request_shutdown)(client, request_id)
    }
    pub unsafe fn cbf_bridge_client_confirm_shutdown(
        &self,
        client: *mut CbfBridgeClientHandle,
        request_id: u64,
        proceed: bool,
    ) -> bool {
        (self.cbf_bridge_client_confirm_shutdown)(client, request_id, proceed)
    }
    pub unsafe fn cbf_bridge_client_force_shutdown(
        &self,
        client: *mut CbfBridgeClientHandle,
    ) -> bool {
        (self.cbf_bridge_client_force_shutdown)(client)
    }
}
