/* automatically generated by rust-bindgen 0.72.1 */

#![allow(
    dead_code,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    improper_ctypes
)]

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfBridgeClientHandle {
    _unused: [u8; 0],
}
pub const CbfEventKind_kEventNone: CbfEventKind = 0;
pub const CbfEventKind_kEventSurfaceHandleUpdated: CbfEventKind = 1;
pub const CbfEventKind_kEventTabCreated: CbfEventKind = 2;
pub const CbfEventKind_kEventImeBoundsUpdated: CbfEventKind = 3;
pub const CbfEventKind_kEventShutdownBlocked: CbfEventKind = 4;
pub const CbfEventKind_kEventShutdownProceeding: CbfEventKind = 5;
pub const CbfEventKind_kEventShutdownCancelled: CbfEventKind = 6;
pub const CbfEventKind_kEventContextMenuRequested: CbfEventKind = 7;
pub const CbfEventKind_kEventNewTabRequested: CbfEventKind = 8;
pub const CbfEventKind_kEventBeforeUnloadDialogRequested: CbfEventKind = 9;
pub const CbfEventKind_kEventTabClosed: CbfEventKind = 10;
pub const CbfEventKind_kEventNavigationStateChanged: CbfEventKind = 11;
pub const CbfEventKind_kEventTabResizeAcknowledged: CbfEventKind = 12;
pub const CbfEventKind_kEventCursorChanged: CbfEventKind = 13;
pub const CbfEventKind_kEventTabDomHtmlRead: CbfEventKind = 14;
pub const CbfEventKind_kEventDragStartRequested: CbfEventKind = 15;
pub const CbfEventKind_kEventTitleUpdated: CbfEventKind = 16;
pub const CbfEventKind_kEventFaviconUrlUpdated: CbfEventKind = 17;
pub const CbfEventKind_kEventDevToolsOpened: CbfEventKind = 18;
pub const CbfEventKind_kEventExtensionsListed: CbfEventKind = 19;
pub const CbfEventKind_kEventExtensionRuntimeWarning: CbfEventKind = 22;
pub const CbfEventKind_kEventPromptUiOpened: CbfEventKind = 23;
pub const CbfEventKind_kEventPromptUiClosed: CbfEventKind = 24;
pub const CbfEventKind_kEventTabOpenRequested: CbfEventKind = 25;
pub const CbfEventKind_kEventTabOpenResolved: CbfEventKind = 26;
pub const CbfEventKind_kEventPromptUiRequested: CbfEventKind = 27;
pub const CbfEventKind_kEventPromptUiResolved: CbfEventKind = 28;
pub const CbfEventKind_kEventDownloadCreated: CbfEventKind = 29;
pub const CbfEventKind_kEventDownloadUpdated: CbfEventKind = 30;
pub const CbfEventKind_kEventDownloadCompleted: CbfEventKind = 31;
pub const CbfEventKind_kEventExtensionPopupOpened: CbfEventKind = 32;
pub const CbfEventKind_kEventExtensionPopupSurfaceHandleUpdated: CbfEventKind = 33;
pub const CbfEventKind_kEventExtensionPopupPreferredSizeChanged: CbfEventKind = 34;
pub const CbfEventKind_kEventExtensionPopupClosed: CbfEventKind = 35;
pub const CbfEventKind_kEventExtensionPopupImeBoundsUpdated: CbfEventKind = 36;
pub const CbfEventKind_kEventExtensionPopupContextMenuRequested: CbfEventKind = 37;
pub const CbfEventKind_kEventExtensionPopupCursorChanged: CbfEventKind = 38;
pub const CbfEventKind_kEventExtensionPopupTitleUpdated: CbfEventKind = 39;
pub const CbfEventKind_kEventExtensionPopupJavaScriptDialogRequested: CbfEventKind = 40;
pub const CbfEventKind_kEventExtensionPopupCloseRequested: CbfEventKind = 41;
pub const CbfEventKind_kEventExtensionPopupRenderProcessGone: CbfEventKind = 42;
pub const CbfEventKind_kEventJavaScriptDialogRequested: CbfEventKind = 43;
pub const CbfEventKind_kEventChoiceMenuRequested: CbfEventKind = 44;
pub const CbfEventKind_kEventExtensionPopupChoiceMenuRequested: CbfEventKind = 45;
pub const CbfEventKind_kEventTabIpcMessageReceived: CbfEventKind = 46;
pub const CbfEventKind_kEventCustomSchemeRequestReceived: CbfEventKind = 47;
pub const CbfEventKind_kEventFindReply: CbfEventKind = 49;
pub const CbfEventKind_kEventExternalDragOperationChanged: CbfEventKind = 48;
pub type CbfEventKind = ::std::os::raw::c_uint;
pub const CbfBridgeEventWaitStatus_kCbfBridgeEventWaitStatusEventAvailable:
    CbfBridgeEventWaitStatus = 0;
pub const CbfBridgeEventWaitStatus_kCbfBridgeEventWaitStatusTimedOut: CbfBridgeEventWaitStatus = 1;
pub const CbfBridgeEventWaitStatus_kCbfBridgeEventWaitStatusDisconnected: CbfBridgeEventWaitStatus =
    2;
pub const CbfBridgeEventWaitStatus_kCbfBridgeEventWaitStatusClosed: CbfBridgeEventWaitStatus = 3;
pub type CbfBridgeEventWaitStatus = ::std::os::raw::c_uint;
pub const CbfExtensionInstallPromptResult_kCbfExtensionInstallPromptResultAccepted:
    CbfExtensionInstallPromptResult = 0;
pub const CbfExtensionInstallPromptResult_kCbfExtensionInstallPromptResultAcceptedWithWithheldPermissions : CbfExtensionInstallPromptResult = 1 ;
pub const CbfExtensionInstallPromptResult_kCbfExtensionInstallPromptResultUserCanceled:
    CbfExtensionInstallPromptResult = 2;
pub const CbfExtensionInstallPromptResult_kCbfExtensionInstallPromptResultAborted:
    CbfExtensionInstallPromptResult = 3;
pub type CbfExtensionInstallPromptResult = ::std::os::raw::c_uint;
pub const CbfExtensionUninstallPromptResult_kCbfExtensionUninstallPromptResultAccepted:
    CbfExtensionUninstallPromptResult = 0;
pub const CbfExtensionUninstallPromptResult_kCbfExtensionUninstallPromptResultUserCanceled:
    CbfExtensionUninstallPromptResult = 1;
pub const CbfExtensionUninstallPromptResult_kCbfExtensionUninstallPromptResultAborted:
    CbfExtensionUninstallPromptResult = 2;
pub const CbfExtensionUninstallPromptResult_kCbfExtensionUninstallPromptResultFailed:
    CbfExtensionUninstallPromptResult = 3;
pub type CbfExtensionUninstallPromptResult = ::std::os::raw::c_uint;
pub const CbfPromptUiKind_kCbfPromptUiKindUnknown: CbfPromptUiKind = 0;
pub const CbfPromptUiKind_kCbfPromptUiKindPermissionPrompt: CbfPromptUiKind = 1;
pub const CbfPromptUiKind_kCbfPromptUiKindDownloadPrompt: CbfPromptUiKind = 2;
pub const CbfPromptUiKind_kCbfPromptUiKindExtensionInstallPrompt: CbfPromptUiKind = 3;
pub const CbfPromptUiKind_kCbfPromptUiKindExtensionUninstallPrompt: CbfPromptUiKind = 4;
pub const CbfPromptUiKind_kCbfPromptUiKindPrintPreviewDialog: CbfPromptUiKind = 5;
pub const CbfPromptUiKind_kCbfPromptUiKindFormResubmissionPrompt: CbfPromptUiKind = 6;
pub type CbfPromptUiKind = ::std::os::raw::c_uint;
pub const CbfPromptUiCloseReason_kCbfPromptUiCloseReasonUnknown: CbfPromptUiCloseReason = 0;
pub const CbfPromptUiCloseReason_kCbfPromptUiCloseReasonUserCanceled: CbfPromptUiCloseReason = 1;
pub const CbfPromptUiCloseReason_kCbfPromptUiCloseReasonHostForced: CbfPromptUiCloseReason = 2;
pub const CbfPromptUiCloseReason_kCbfPromptUiCloseReasonSystemDismissed: CbfPromptUiCloseReason = 3;
pub type CbfPromptUiCloseReason = ::std::os::raw::c_uint;
pub const CbfFormResubmissionReason_kCbfFormResubmissionReasonUnknown: CbfFormResubmissionReason =
    0;
pub const CbfFormResubmissionReason_kCbfFormResubmissionReasonReload: CbfFormResubmissionReason = 1;
pub const CbfFormResubmissionReason_kCbfFormResubmissionReasonBackForward:
    CbfFormResubmissionReason = 2;
pub const CbfFormResubmissionReason_kCbfFormResubmissionReasonOther: CbfFormResubmissionReason = 3;
pub type CbfFormResubmissionReason = ::std::os::raw::c_uint;
pub const CbfPromptUiPermissionType_kCbfPromptUiPermissionTypeUnknown: CbfPromptUiPermissionType =
    0;
pub const CbfPromptUiPermissionType_kCbfPromptUiPermissionTypeGeolocation:
    CbfPromptUiPermissionType = 1;
pub const CbfPromptUiPermissionType_kCbfPromptUiPermissionTypeNotifications:
    CbfPromptUiPermissionType = 2;
pub const CbfPromptUiPermissionType_kCbfPromptUiPermissionTypeAudioCapture:
    CbfPromptUiPermissionType = 3;
pub const CbfPromptUiPermissionType_kCbfPromptUiPermissionTypeVideoCapture:
    CbfPromptUiPermissionType = 4;
pub type CbfPromptUiPermissionType = ::std::os::raw::c_uint;
pub const CbfPromptUiResolutionResult_kCbfPromptUiResolutionResultUnknown:
    CbfPromptUiResolutionResult = 0;
pub const CbfPromptUiResolutionResult_kCbfPromptUiResolutionResultAllowed:
    CbfPromptUiResolutionResult = 1;
pub const CbfPromptUiResolutionResult_kCbfPromptUiResolutionResultDenied:
    CbfPromptUiResolutionResult = 2;
pub const CbfPromptUiResolutionResult_kCbfPromptUiResolutionResultAborted:
    CbfPromptUiResolutionResult = 3;
pub type CbfPromptUiResolutionResult = ::std::os::raw::c_uint;
pub const CbfPromptUiDialogResult_kCbfPromptUiDialogResultUnknown: CbfPromptUiDialogResult = 0;
pub const CbfPromptUiDialogResult_kCbfPromptUiDialogResultProceeded: CbfPromptUiDialogResult = 1;
pub const CbfPromptUiDialogResult_kCbfPromptUiDialogResultCanceled: CbfPromptUiDialogResult = 2;
pub const CbfPromptUiDialogResult_kCbfPromptUiDialogResultAborted: CbfPromptUiDialogResult = 3;
pub type CbfPromptUiDialogResult = ::std::os::raw::c_uint;
pub const CbfDownloadPromptResult_kCbfDownloadPromptResultAllowed: CbfDownloadPromptResult = 1;
pub const CbfDownloadPromptResult_kCbfDownloadPromptResultDenied: CbfDownloadPromptResult = 2;
pub const CbfDownloadPromptResult_kCbfDownloadPromptResultAborted: CbfDownloadPromptResult = 3;
pub type CbfDownloadPromptResult = ::std::os::raw::c_uint;
pub const CbfDownloadPromptReason_kCbfDownloadPromptReasonNone: CbfDownloadPromptReason = 0;
pub const CbfDownloadPromptReason_kCbfDownloadPromptReasonUnexpected: CbfDownloadPromptReason = 1;
pub const CbfDownloadPromptReason_kCbfDownloadPromptReasonSaveAs: CbfDownloadPromptReason = 2;
pub const CbfDownloadPromptReason_kCbfDownloadPromptReasonPreference: CbfDownloadPromptReason = 3;
pub const CbfDownloadPromptReason_kCbfDownloadPromptReasonNameTooLong: CbfDownloadPromptReason = 4;
pub const CbfDownloadPromptReason_kCbfDownloadPromptReasonTargetConflict: CbfDownloadPromptReason =
    5;
pub const CbfDownloadPromptReason_kCbfDownloadPromptReasonTargetPathNotWriteable:
    CbfDownloadPromptReason = 6;
pub const CbfDownloadPromptReason_kCbfDownloadPromptReasonTargetNoSpace: CbfDownloadPromptReason =
    7;
pub const CbfDownloadPromptReason_kCbfDownloadPromptReasonDlpBlocked: CbfDownloadPromptReason = 8;
pub const CbfDownloadPromptReason_kCbfDownloadPromptReasonUnknown: CbfDownloadPromptReason = 255;
pub type CbfDownloadPromptReason = ::std::os::raw::c_uint;
pub const CbfDownloadState_kCbfDownloadStateUnknown: CbfDownloadState = 0;
pub const CbfDownloadState_kCbfDownloadStateInProgress: CbfDownloadState = 1;
pub const CbfDownloadState_kCbfDownloadStatePaused: CbfDownloadState = 2;
pub const CbfDownloadState_kCbfDownloadStateCompleted: CbfDownloadState = 3;
pub const CbfDownloadState_kCbfDownloadStateCancelled: CbfDownloadState = 4;
pub const CbfDownloadState_kCbfDownloadStateInterrupted: CbfDownloadState = 5;
pub type CbfDownloadState = ::std::os::raw::c_uint;
pub const CbfDownloadOutcome_kCbfDownloadOutcomeUnknown: CbfDownloadOutcome = 0;
pub const CbfDownloadOutcome_kCbfDownloadOutcomeSucceeded: CbfDownloadOutcome = 1;
pub const CbfDownloadOutcome_kCbfDownloadOutcomeCancelled: CbfDownloadOutcome = 2;
pub const CbfDownloadOutcome_kCbfDownloadOutcomeInterrupted: CbfDownloadOutcome = 3;
pub type CbfDownloadOutcome = ::std::os::raw::c_uint;
pub const CbfIconDataKind_kCbfIconDataKindNone: CbfIconDataKind = 0;
pub const CbfIconDataKind_kCbfIconDataKindUrl: CbfIconDataKind = 1;
pub const CbfIconDataKind_kCbfIconDataKindPng: CbfIconDataKind = 2;
pub const CbfIconDataKind_kCbfIconDataKindBinary: CbfIconDataKind = 3;
pub type CbfIconDataKind = ::std::os::raw::c_uint;
pub const CbfTabOpenHint_kCbfTabOpenHintUnknown: CbfTabOpenHint = 0;
pub const CbfTabOpenHint_kCbfTabOpenHintCurrentContext: CbfTabOpenHint = 1;
pub const CbfTabOpenHint_kCbfTabOpenHintNewForegroundContext: CbfTabOpenHint = 2;
pub const CbfTabOpenHint_kCbfTabOpenHintNewBackgroundContext: CbfTabOpenHint = 3;
pub const CbfTabOpenHint_kCbfTabOpenHintNewWindow: CbfTabOpenHint = 4;
pub const CbfTabOpenHint_kCbfTabOpenHintPopup: CbfTabOpenHint = 5;
pub type CbfTabOpenHint = ::std::os::raw::c_uint;
pub const CbfTabOpenResponseKind_kCbfTabOpenResponseAllowNewContext: CbfTabOpenResponseKind = 0;
pub const CbfTabOpenResponseKind_kCbfTabOpenResponseAllowExistingContext: CbfTabOpenResponseKind =
    1;
pub const CbfTabOpenResponseKind_kCbfTabOpenResponseDeny: CbfTabOpenResponseKind = 2;
pub type CbfTabOpenResponseKind = ::std::os::raw::c_uint;
pub const CbfTabOpenResult_kCbfTabOpenResultOpenedNewContext: CbfTabOpenResult = 0;
pub const CbfTabOpenResult_kCbfTabOpenResultOpenedExistingContext: CbfTabOpenResult = 1;
pub const CbfTabOpenResult_kCbfTabOpenResultDenied: CbfTabOpenResult = 2;
pub const CbfTabOpenResult_kCbfTabOpenResultAborted: CbfTabOpenResult = 3;
pub type CbfTabOpenResult = ::std::os::raw::c_uint;
pub const CbfTabVisibility_kCbfTabVisibilityVisible: CbfTabVisibility = 0;
pub const CbfTabVisibility_kCbfTabVisibilityHidden: CbfTabVisibility = 1;
pub type CbfTabVisibility = ::std::os::raw::c_uint;
pub const CbfSurfaceHandleKind_kSurfaceHandleNone: CbfSurfaceHandleKind = 0;
pub const CbfSurfaceHandleKind_kSurfaceHandleMacCaContextId: CbfSurfaceHandleKind = 1;
pub const CbfSurfaceHandleKind_kSurfaceHandleWindowsHwnd: CbfSurfaceHandleKind = 2;
pub type CbfSurfaceHandleKind = ::std::os::raw::c_uint;
pub const CbfKeyEventType_kCbfKeyEventRawKeyDown: CbfKeyEventType = 0;
pub const CbfKeyEventType_kCbfKeyEventKeyDown: CbfKeyEventType = 1;
pub const CbfKeyEventType_kCbfKeyEventKeyUp: CbfKeyEventType = 2;
pub const CbfKeyEventType_kCbfKeyEventChar: CbfKeyEventType = 3;
pub type CbfKeyEventType = ::std::os::raw::c_uint;
pub const CbfMouseEventType_kCbfMouseEventDown: CbfMouseEventType = 0;
pub const CbfMouseEventType_kCbfMouseEventUp: CbfMouseEventType = 1;
pub const CbfMouseEventType_kCbfMouseEventMove: CbfMouseEventType = 2;
pub const CbfMouseEventType_kCbfMouseEventEnter: CbfMouseEventType = 3;
pub const CbfMouseEventType_kCbfMouseEventLeave: CbfMouseEventType = 4;
pub type CbfMouseEventType = ::std::os::raw::c_uint;
pub const CbfMouseButton_kCbfMouseButtonNone: CbfMouseButton = 0;
pub const CbfMouseButton_kCbfMouseButtonLeft: CbfMouseButton = 1;
pub const CbfMouseButton_kCbfMouseButtonMiddle: CbfMouseButton = 2;
pub const CbfMouseButton_kCbfMouseButtonRight: CbfMouseButton = 3;
pub const CbfMouseButton_kCbfMouseButtonBack: CbfMouseButton = 4;
pub const CbfMouseButton_kCbfMouseButtonForward: CbfMouseButton = 5;
pub type CbfMouseButton = ::std::os::raw::c_uint;
pub const CbfPointerType_kCbfPointerTypeUnknown: CbfPointerType = 0;
pub const CbfPointerType_kCbfPointerTypeMouse: CbfPointerType = 1;
pub const CbfPointerType_kCbfPointerTypePen: CbfPointerType = 2;
pub const CbfPointerType_kCbfPointerTypeTouch: CbfPointerType = 3;
pub const CbfPointerType_kCbfPointerTypeEraser: CbfPointerType = 4;
pub type CbfPointerType = ::std::os::raw::c_uint;
pub const CbfScrollGranularity_kCbfScrollByPrecisePixel: CbfScrollGranularity = 0;
pub const CbfScrollGranularity_kCbfScrollByPixel: CbfScrollGranularity = 1;
pub const CbfScrollGranularity_kCbfScrollByLine: CbfScrollGranularity = 2;
pub const CbfScrollGranularity_kCbfScrollByPage: CbfScrollGranularity = 3;
pub const CbfScrollGranularity_kCbfScrollByDocument: CbfScrollGranularity = 4;
pub type CbfScrollGranularity = ::std::os::raw::c_uint;
pub const CbfImeTextSpanType_kCbfImeTextSpanTypeComposition: CbfImeTextSpanType = 0;
pub const CbfImeTextSpanType_kCbfImeTextSpanTypeSuggestion: CbfImeTextSpanType = 1;
pub const CbfImeTextSpanType_kCbfImeTextSpanTypeMisspellingSuggestion: CbfImeTextSpanType = 2;
pub const CbfImeTextSpanType_kCbfImeTextSpanTypeAutocorrect: CbfImeTextSpanType = 3;
pub const CbfImeTextSpanType_kCbfImeTextSpanTypeGrammarSuggestion: CbfImeTextSpanType = 4;
pub type CbfImeTextSpanType = ::std::os::raw::c_uint;
pub const CbfImeTextSpanThickness_kCbfImeTextSpanThicknessNone: CbfImeTextSpanThickness = 0;
pub const CbfImeTextSpanThickness_kCbfImeTextSpanThicknessThin: CbfImeTextSpanThickness = 1;
pub const CbfImeTextSpanThickness_kCbfImeTextSpanThicknessThick: CbfImeTextSpanThickness = 2;
pub type CbfImeTextSpanThickness = ::std::os::raw::c_uint;
pub const CbfImeTextSpanUnderlineStyle_kCbfImeTextSpanUnderlineStyleNone:
    CbfImeTextSpanUnderlineStyle = 0;
pub const CbfImeTextSpanUnderlineStyle_kCbfImeTextSpanUnderlineStyleSolid:
    CbfImeTextSpanUnderlineStyle = 1;
pub const CbfImeTextSpanUnderlineStyle_kCbfImeTextSpanUnderlineStyleDot:
    CbfImeTextSpanUnderlineStyle = 2;
pub const CbfImeTextSpanUnderlineStyle_kCbfImeTextSpanUnderlineStyleDash:
    CbfImeTextSpanUnderlineStyle = 3;
pub const CbfImeTextSpanUnderlineStyle_kCbfImeTextSpanUnderlineStyleSquiggle:
    CbfImeTextSpanUnderlineStyle = 4;
pub type CbfImeTextSpanUnderlineStyle = ::std::os::raw::c_uint;
pub const CbfConfirmCompositionBehavior_kCbfConfirmCompositionDoNotKeepSelection:
    CbfConfirmCompositionBehavior = 0;
pub const CbfConfirmCompositionBehavior_kCbfConfirmCompositionKeepSelection:
    CbfConfirmCompositionBehavior = 1;
pub type CbfConfirmCompositionBehavior = ::std::os::raw::c_uint;
pub const CbfBeforeUnloadReason_kCbfBeforeUnloadReasonUnknown: CbfBeforeUnloadReason = 0;
pub const CbfBeforeUnloadReason_kCbfBeforeUnloadReasonCloseTab: CbfBeforeUnloadReason = 1;
pub const CbfBeforeUnloadReason_kCbfBeforeUnloadReasonNavigate: CbfBeforeUnloadReason = 2;
pub const CbfBeforeUnloadReason_kCbfBeforeUnloadReasonReload: CbfBeforeUnloadReason = 3;
pub const CbfBeforeUnloadReason_kCbfBeforeUnloadReasonWindowClose: CbfBeforeUnloadReason = 4;
pub type CbfBeforeUnloadReason = ::std::os::raw::c_uint;
pub const CbfJavaScriptDialogType_kCbfJavaScriptDialogAlert: CbfJavaScriptDialogType = 0;
pub const CbfJavaScriptDialogType_kCbfJavaScriptDialogConfirm: CbfJavaScriptDialogType = 1;
pub const CbfJavaScriptDialogType_kCbfJavaScriptDialogPrompt: CbfJavaScriptDialogType = 2;
pub const CbfJavaScriptDialogType_kCbfJavaScriptDialogBeforeUnload: CbfJavaScriptDialogType = 3;
pub type CbfJavaScriptDialogType = ::std::os::raw::c_uint;
pub const CbfCursorType_kCbfCursorDefault: CbfCursorType = 0;
pub const CbfCursorType_kCbfCursorCrosshair: CbfCursorType = 1;
pub const CbfCursorType_kCbfCursorPointer: CbfCursorType = 2;
pub const CbfCursorType_kCbfCursorMove: CbfCursorType = 3;
pub const CbfCursorType_kCbfCursorText: CbfCursorType = 4;
pub const CbfCursorType_kCbfCursorWait: CbfCursorType = 5;
pub const CbfCursorType_kCbfCursorHelp: CbfCursorType = 6;
pub const CbfCursorType_kCbfCursorProgress: CbfCursorType = 7;
pub const CbfCursorType_kCbfCursorNotAllowed: CbfCursorType = 8;
pub const CbfCursorType_kCbfCursorContextMenu: CbfCursorType = 9;
pub const CbfCursorType_kCbfCursorCell: CbfCursorType = 10;
pub const CbfCursorType_kCbfCursorVerticalText: CbfCursorType = 11;
pub const CbfCursorType_kCbfCursorAlias: CbfCursorType = 12;
pub const CbfCursorType_kCbfCursorCopy: CbfCursorType = 13;
pub const CbfCursorType_kCbfCursorNoDrop: CbfCursorType = 14;
pub const CbfCursorType_kCbfCursorGrab: CbfCursorType = 15;
pub const CbfCursorType_kCbfCursorGrabbing: CbfCursorType = 16;
pub const CbfCursorType_kCbfCursorAllScroll: CbfCursorType = 17;
pub const CbfCursorType_kCbfCursorZoomIn: CbfCursorType = 18;
pub const CbfCursorType_kCbfCursorZoomOut: CbfCursorType = 19;
pub const CbfCursorType_kCbfCursorEResize: CbfCursorType = 20;
pub const CbfCursorType_kCbfCursorNResize: CbfCursorType = 21;
pub const CbfCursorType_kCbfCursorNeResize: CbfCursorType = 22;
pub const CbfCursorType_kCbfCursorNwResize: CbfCursorType = 23;
pub const CbfCursorType_kCbfCursorSResize: CbfCursorType = 24;
pub const CbfCursorType_kCbfCursorSeResize: CbfCursorType = 25;
pub const CbfCursorType_kCbfCursorSwResize: CbfCursorType = 26;
pub const CbfCursorType_kCbfCursorWResize: CbfCursorType = 27;
pub const CbfCursorType_kCbfCursorEwResize: CbfCursorType = 28;
pub const CbfCursorType_kCbfCursorNsResize: CbfCursorType = 29;
pub const CbfCursorType_kCbfCursorNeswResize: CbfCursorType = 30;
pub const CbfCursorType_kCbfCursorNwseResize: CbfCursorType = 31;
pub const CbfCursorType_kCbfCursorColResize: CbfCursorType = 32;
pub const CbfCursorType_kCbfCursorRowResize: CbfCursorType = 33;
pub type CbfCursorType = ::std::os::raw::c_uint;
pub const CbfContextMenuItemType_kCbfMenuItemCommand: CbfContextMenuItemType = 0;
pub const CbfContextMenuItemType_kCbfMenuItemCheck: CbfContextMenuItemType = 1;
pub const CbfContextMenuItemType_kCbfMenuItemRadio: CbfContextMenuItemType = 2;
pub const CbfContextMenuItemType_kCbfMenuItemSeparator: CbfContextMenuItemType = 3;
pub const CbfContextMenuItemType_kCbfMenuItemButtonItem: CbfContextMenuItemType = 4;
pub const CbfContextMenuItemType_kCbfMenuItemSubmenu: CbfContextMenuItemType = 5;
pub const CbfContextMenuItemType_kCbfMenuItemActionableSubmenu: CbfContextMenuItemType = 6;
pub const CbfContextMenuItemType_kCbfMenuItemHighlighted: CbfContextMenuItemType = 7;
pub const CbfContextMenuItemType_kCbfMenuItemTitle: CbfContextMenuItemType = 8;
pub type CbfContextMenuItemType = ::std::os::raw::c_uint;
pub const CbfChoiceMenuItemType_kCbfChoiceMenuItemOption: CbfChoiceMenuItemType = 0;
pub const CbfChoiceMenuItemType_kCbfChoiceMenuItemCheckableOption: CbfChoiceMenuItemType = 1;
pub const CbfChoiceMenuItemType_kCbfChoiceMenuItemGroup: CbfChoiceMenuItemType = 2;
pub const CbfChoiceMenuItemType_kCbfChoiceMenuItemSeparator: CbfChoiceMenuItemType = 3;
pub const CbfChoiceMenuItemType_kCbfChoiceMenuItemSubMenu: CbfChoiceMenuItemType = 4;
pub type CbfChoiceMenuItemType = ::std::os::raw::c_uint;
pub const CbfChoiceMenuTextDirection_kCbfChoiceMenuTextDirectionLeftToRight:
    CbfChoiceMenuTextDirection = 0;
pub const CbfChoiceMenuTextDirection_kCbfChoiceMenuTextDirectionRightToLeft:
    CbfChoiceMenuTextDirection = 1;
pub type CbfChoiceMenuTextDirection = ::std::os::raw::c_uint;
pub const CbfIpcPayloadKind_kCbfIpcPayloadText: CbfIpcPayloadKind = 0;
pub const CbfIpcPayloadKind_kCbfIpcPayloadBinary: CbfIpcPayloadKind = 1;
pub type CbfIpcPayloadKind = ::std::os::raw::c_uint;
pub const CbfIpcMessageType_kCbfIpcMessageRequest: CbfIpcMessageType = 0;
pub const CbfIpcMessageType_kCbfIpcMessageResponse: CbfIpcMessageType = 1;
pub const CbfIpcMessageType_kCbfIpcMessageEvent: CbfIpcMessageType = 2;
pub type CbfIpcMessageType = ::std::os::raw::c_uint;
pub const CbfIpcErrorCode_kCbfIpcErrorNone: CbfIpcErrorCode = 0;
pub const CbfIpcErrorCode_kCbfIpcErrorTimeout: CbfIpcErrorCode = 1;
pub const CbfIpcErrorCode_kCbfIpcErrorAborted: CbfIpcErrorCode = 2;
pub const CbfIpcErrorCode_kCbfIpcErrorDisconnected: CbfIpcErrorCode = 3;
pub const CbfIpcErrorCode_kCbfIpcErrorIpcDisabled: CbfIpcErrorCode = 4;
pub const CbfIpcErrorCode_kCbfIpcErrorContextClosed: CbfIpcErrorCode = 5;
pub const CbfIpcErrorCode_kCbfIpcErrorRemoteError: CbfIpcErrorCode = 6;
pub const CbfIpcErrorCode_kCbfIpcErrorProtocolError: CbfIpcErrorCode = 7;
pub type CbfIpcErrorCode = ::std::os::raw::c_uint;
pub const CbfCustomSchemeResponseResult_kCbfCustomSchemeResponseResultOk:
    CbfCustomSchemeResponseResult = 0;
pub const CbfCustomSchemeResponseResult_kCbfCustomSchemeResponseResultNotFound:
    CbfCustomSchemeResponseResult = 1;
pub const CbfCustomSchemeResponseResult_kCbfCustomSchemeResponseResultAborted:
    CbfCustomSchemeResponseResult = 2;
pub type CbfCustomSchemeResponseResult = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CbfSurfaceHandle {
    pub kind: u8,
    pub ca_context_id: u32,
    pub win_hwnd: u64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfProfileInfo {
    pub profile_id: *mut ::std::os::raw::c_char,
    pub profile_path: *mut ::std::os::raw::c_char,
    pub display_name: *mut ::std::os::raw::c_char,
    pub is_default: bool,
}
impl Default for CbfProfileInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfProfileList {
    pub profiles: *mut CbfProfileInfo,
    pub len: u32,
}
impl Default for CbfProfileList {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfCommandList {
    pub items: *mut *const ::std::os::raw::c_char,
    pub len: u32,
}
impl Default for CbfCommandList {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfKeyEvent {
    pub tab_id: u64,
    pub type_: u8,
    pub modifiers: u32,
    pub windows_key_code: i32,
    pub native_key_code: i32,
    pub dom_code: *const ::std::os::raw::c_char,
    pub dom_key: *const ::std::os::raw::c_char,
    pub text: *const ::std::os::raw::c_char,
    pub unmodified_text: *const ::std::os::raw::c_char,
    pub auto_repeat: bool,
    pub is_keypad: bool,
    pub is_system_key: bool,
    pub location: i32,
}
impl Default for CbfKeyEvent {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CbfMouseEvent {
    pub tab_id: u64,
    pub type_: u8,
    pub modifiers: u32,
    pub button: u8,
    pub click_count: i32,
    pub position_in_widget_x: f32,
    pub position_in_widget_y: f32,
    pub position_in_screen_x: f32,
    pub position_in_screen_y: f32,
    pub movement_x: f32,
    pub movement_y: f32,
    pub is_raw_movement_event: bool,
    pub pointer_type: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CbfMouseWheelEvent {
    pub tab_id: u64,
    pub modifiers: u32,
    pub position_in_widget_x: f32,
    pub position_in_widget_y: f32,
    pub position_in_screen_x: f32,
    pub position_in_screen_y: f32,
    pub movement_x: f32,
    pub movement_y: f32,
    pub is_raw_movement_event: bool,
    pub delta_x: f32,
    pub delta_y: f32,
    pub wheel_ticks_x: f32,
    pub wheel_ticks_y: f32,
    pub phase: u32,
    pub momentum_phase: u32,
    pub delta_units: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfDragUrlInfo {
    pub url: *mut ::std::os::raw::c_char,
    pub title: *mut ::std::os::raw::c_char,
}
impl Default for CbfDragUrlInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfDragUrlInfoList {
    pub items: *const CbfDragUrlInfo,
    pub len: u32,
}
impl Default for CbfDragUrlInfoList {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfStringList {
    pub items: *mut *mut ::std::os::raw::c_char,
    pub len: u32,
}
impl Default for CbfStringList {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfIconData {
    pub kind: u8,
    pub url: *mut ::std::os::raw::c_char,
    pub bytes: *const u8,
    pub len: u32,
    pub media_type: *mut ::std::os::raw::c_char,
}
impl Default for CbfIconData {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfExtensionInfo {
    pub id: *mut ::std::os::raw::c_char,
    pub name: *mut ::std::os::raw::c_char,
    pub version: *mut ::std::os::raw::c_char,
    pub enabled: bool,
    pub permission_names: CbfStringList,
    pub icon: CbfIconData,
}
impl Default for CbfExtensionInfo {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfExtensionInfoList {
    pub items: *mut CbfExtensionInfo,
    pub len: u32,
}
impl Default for CbfExtensionInfoList {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfStringPair {
    pub key: *mut ::std::os::raw::c_char,
    pub value: *mut ::std::os::raw::c_char,
}
impl Default for CbfStringPair {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfStringPairList {
    pub items: *mut CbfStringPair,
    pub len: u32,
}
impl Default for CbfStringPairList {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfDragData {
    pub text: *mut ::std::os::raw::c_char,
    pub html: *mut ::std::os::raw::c_char,
    pub html_base_url: *mut ::std::os::raw::c_char,
    pub url_infos: CbfDragUrlInfoList,
    pub filenames: CbfStringList,
    pub file_mime_types: CbfStringList,
    pub custom_data: CbfStringPairList,
}
impl Default for CbfDragData {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfDragImage {
    pub png_bytes: *const u8,
    pub png_len: u32,
    pub pixel_width: u32,
    pub pixel_height: u32,
    pub scale: f32,
    pub cursor_offset_x: i32,
    pub cursor_offset_y: i32,
}
impl Default for CbfDragImage {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfDragStartRequest {
    pub session_id: u64,
    pub tab_id: u64,
    pub allowed_operations: u32,
    pub source_origin: *mut ::std::os::raw::c_char,
    pub data: CbfDragData,
    pub image: CbfDragImage,
}
impl Default for CbfDragStartRequest {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CbfDragUpdate {
    pub session_id: u64,
    pub tab_id: u64,
    pub allowed_operations: u32,
    pub modifiers: u32,
    pub position_in_widget_x: f32,
    pub position_in_widget_y: f32,
    pub position_in_screen_x: f32,
    pub position_in_screen_y: f32,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CbfDragDrop {
    pub session_id: u64,
    pub tab_id: u64,
    pub modifiers: u32,
    pub position_in_widget_x: f32,
    pub position_in_widget_y: f32,
    pub position_in_screen_x: f32,
    pub position_in_screen_y: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfExternalDragEnter {
    pub tab_id: u64,
    pub data: CbfDragData,
    pub allowed_operations: u32,
    pub modifiers: u32,
    pub position_in_widget_x: f32,
    pub position_in_widget_y: f32,
    pub position_in_screen_x: f32,
    pub position_in_screen_y: f32,
}
impl Default for CbfExternalDragEnter {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CbfExternalDragUpdate {
    pub tab_id: u64,
    pub allowed_operations: u32,
    pub modifiers: u32,
    pub position_in_widget_x: f32,
    pub position_in_widget_y: f32,
    pub position_in_screen_x: f32,
    pub position_in_screen_y: f32,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CbfExternalDragDrop {
    pub tab_id: u64,
    pub modifiers: u32,
    pub position_in_widget_x: f32,
    pub position_in_widget_y: f32,
    pub position_in_screen_x: f32,
    pub position_in_screen_y: f32,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CbfRect {
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfRectList {
    pub items: *const CbfRect,
    pub len: u32,
}
impl Default for CbfRectList {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfImeCompositionBounds {
    pub range_start: i32,
    pub range_end: i32,
    pub character_bounds: CbfRectList,
}
impl Default for CbfImeCompositionBounds {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CbfTextSelectionBounds {
    pub range_start: i32,
    pub range_end: i32,
    pub caret_rect: CbfRect,
    pub first_selection_rect: CbfRect,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfImeBoundsUpdate {
    pub has_composition: bool,
    pub composition: CbfImeCompositionBounds,
    pub has_selection: bool,
    pub selection: CbfTextSelectionBounds,
}
impl Default for CbfImeBoundsUpdate {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfTabIdList {
    pub items: *const u64,
    pub len: u32,
}
impl Default for CbfTabIdList {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfContextMenuIcon {
    pub png_bytes: *const u8,
    pub len: u32,
    pub width: u32,
    pub height: u32,
}
impl Default for CbfContextMenuIcon {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfContextMenuItemList {
    pub items: *const CbfContextMenuItem,
    pub len: u32,
}
impl Default for CbfContextMenuItemList {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfContextMenuItem {
    pub type_: u8,
    pub command_id: i32,
    pub label: *mut ::std::os::raw::c_char,
    pub secondary_label: *mut ::std::os::raw::c_char,
    pub minor_text: *mut ::std::os::raw::c_char,
    pub accessible_name: *mut ::std::os::raw::c_char,
    pub enabled: bool,
    pub visible: bool,
    pub checked: bool,
    pub group_id: i32,
    pub is_new_feature: bool,
    pub is_alerted: bool,
    pub may_have_mnemonics: bool,
    pub has_accelerator: bool,
    pub accelerator_key_equivalent: *mut ::std::os::raw::c_char,
    pub accelerator_modifier_mask: u32,
    pub icon: CbfContextMenuIcon,
    pub minor_icon: CbfContextMenuIcon,
    pub submenu: CbfContextMenuItemList,
}
impl Default for CbfContextMenuItem {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfContextMenu {
    pub menu_id: u64,
    pub x: i32,
    pub y: i32,
    pub source_type: u32,
    pub items: CbfContextMenuItemList,
}
impl Default for CbfContextMenu {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfChoiceMenuItemList {
    pub items: *const CbfChoiceMenuItem,
    pub len: u32,
}
impl Default for CbfChoiceMenuItemList {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfChoiceMenuItem {
    pub type_: u8,
    pub label: *mut ::std::os::raw::c_char,
    pub tool_tip: *mut ::std::os::raw::c_char,
    pub action: u32,
    pub text_direction: u8,
    pub has_text_direction_override: bool,
    pub enabled: bool,
    pub checked: bool,
    pub children: CbfChoiceMenuItemList,
}
impl Default for CbfChoiceMenuItem {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfChoiceMenu {
    pub request_id: u64,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub item_font_size: f64,
    pub selected_item: i32,
    pub right_aligned: bool,
    pub allow_multiple_selection: bool,
    pub items: CbfChoiceMenuItemList,
}
impl Default for CbfChoiceMenu {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfChoiceMenuSelectedIndices {
    pub items: *const i32,
    pub len: u32,
}
impl Default for CbfChoiceMenuSelectedIndices {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfBridgeEvent {
    pub kind: u8,
    pub tab_id: u64,
    pub inspected_tab_id: u64,
    pub request_id: u64,
    pub extension_popup_id: u64,
    pub width: u32,
    pub height: u32,
    pub beforeunload_reason: u8,
    pub javascript_dialog_type: u8,
    pub cursor_type: u8,
    pub profile_id: *mut ::std::os::raw::c_char,
    pub surface_handle: CbfSurfaceHandle,
    pub ime_bounds: CbfImeBoundsUpdate,
    pub dirty_tab_ids: CbfTabIdList,
    pub context_menu: CbfContextMenu,
    pub choice_menu: CbfChoiceMenu,
    pub target_url: *mut ::std::os::raw::c_char,
    pub url: *mut ::std::os::raw::c_char,
    pub is_popup: bool,
    pub can_go_back: bool,
    pub can_go_forward: bool,
    pub is_loading: bool,
    pub dom_html: *mut ::std::os::raw::c_char,
    pub message: *mut ::std::os::raw::c_char,
    pub default_prompt_text: *mut ::std::os::raw::c_char,
    pub title: *mut ::std::os::raw::c_char,
    pub favicon_url: *mut ::std::os::raw::c_char,
    pub crashed: bool,
    pub drag_operation: u32,
    pub drag_start_request: CbfDragStartRequest,
    pub extensions: CbfExtensionInfoList,
    pub extension_id: *mut ::std::os::raw::c_char,
    pub extension_name: *mut ::std::os::raw::c_char,
    pub triggering_extension_name: *mut ::std::os::raw::c_char,
    pub permission_names: CbfStringList,
    pub extension_install_prompt_result: u8,
    pub extension_install_prompt_detail: *mut ::std::os::raw::c_char,
    pub extension_uninstall_prompt_result: u8,
    pub extension_uninstall_prompt_detail: *mut ::std::os::raw::c_char,
    pub extension_runtime_warning: *mut ::std::os::raw::c_char,
    pub find_number_of_matches: u32,
    pub find_active_match_ordinal: i32,
    pub find_selection_rect: CbfRect,
    pub find_final_update: bool,
    pub prompt_ui_id: u64,
    pub prompt_ui_kind: u8,
    pub prompt_ui_close_reason: u8,
    pub prompt_ui_title: *mut ::std::os::raw::c_char,
    pub prompt_ui_modal: bool,
    pub prompt_ui_has_source_tab_id: bool,
    pub prompt_ui_source_tab_id: u64,
    pub prompt_ui_can_report_abuse: bool,
    pub prompt_ui_report_abuse: bool,
    pub prompt_ui_permission: u8,
    pub prompt_ui_result: u8,
    pub prompt_ui_permission_key: *mut ::std::os::raw::c_char,
    pub prompt_ui_repost_reason: u8,
    pub prompt_ui_repost_target_url: *mut ::std::os::raw::c_char,
    pub download_reason: u8,
    pub download_id: u64,
    pub download_has_source_tab_id: bool,
    pub download_source_tab_id: u64,
    pub download_file_name: *mut ::std::os::raw::c_char,
    pub download_target_path: *mut ::std::os::raw::c_char,
    pub download_suggested_path: *mut ::std::os::raw::c_char,
    pub download_destination_path: *mut ::std::os::raw::c_char,
    pub download_total_bytes: u64,
    pub download_has_total_bytes: bool,
    pub download_received_bytes: u64,
    pub download_can_resume: bool,
    pub download_is_paused: bool,
    pub download_state: u8,
    pub download_outcome: u8,
    pub tab_open_hint: u8,
    pub tab_open_user_gesture: bool,
    pub tab_open_has_source: bool,
    pub tab_open_source_tab_id: u64,
    pub tab_open_result_kind: u8,
    pub tab_open_has_target: bool,
    pub tab_open_target_tab_id: u64,
    pub ipc_channel: *mut ::std::os::raw::c_char,
    pub ipc_message_type: u8,
    pub ipc_payload_kind: u8,
    pub ipc_payload_text: *mut ::std::os::raw::c_char,
    pub ipc_payload_binary: *const u8,
    pub ipc_payload_binary_len: u32,
    pub ipc_content_type: *mut ::std::os::raw::c_char,
    pub ipc_error_code: u8,
    pub custom_scheme_scheme: *mut ::std::os::raw::c_char,
    pub custom_scheme_host: *mut ::std::os::raw::c_char,
    pub custom_scheme_path: *mut ::std::os::raw::c_char,
    pub custom_scheme_query: *mut ::std::os::raw::c_char,
    pub custom_scheme_method: *mut ::std::os::raw::c_char,
}
impl Default for CbfBridgeEvent {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct CbfImeTextSpan {
    pub type_: u8,
    pub start_offset: u32,
    pub end_offset: u32,
    pub underline_color: u32,
    pub thickness: u8,
    pub underline_style: u8,
    pub text_color: u32,
    pub background_color: u32,
    pub suggestion_highlight_color: u32,
    pub remove_on_finish_composing: bool,
    pub interim_char_selection: bool,
    pub should_hide_suggestion_menu: bool,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfImeTextSpanList {
    pub items: *const CbfImeTextSpan,
    pub len: u32,
}
impl Default for CbfImeTextSpanList {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfImeComposition {
    pub tab_id: u64,
    pub text: *const ::std::os::raw::c_char,
    pub selection_start: i32,
    pub selection_end: i32,
    pub replacement_range_start: i32,
    pub replacement_range_end: i32,
    pub spans: CbfImeTextSpanList,
}
impl Default for CbfImeComposition {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CbfImeCommitText {
    pub tab_id: u64,
    pub text: *const ::std::os::raw::c_char,
    pub relative_caret_position: i32,
    pub replacement_range_start: i32,
    pub replacement_range_end: i32,
    pub spans: CbfImeTextSpanList,
}
impl Default for CbfImeCommitText {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub const CbfEditAction_kCbfEditActionUndo: CbfEditAction = 0;
pub const CbfEditAction_kCbfEditActionRedo: CbfEditAction = 1;
pub const CbfEditAction_kCbfEditActionCut: CbfEditAction = 2;
pub const CbfEditAction_kCbfEditActionCopy: CbfEditAction = 3;
pub const CbfEditAction_kCbfEditActionPaste: CbfEditAction = 4;
pub const CbfEditAction_kCbfEditActionSelectAll: CbfEditAction = 5;
pub type CbfEditAction = ::std::os::raw::c_uint;
pub const CbfStopFindAction_kCbfStopFindActionClearSelection: CbfStopFindAction = 0;
pub const CbfStopFindAction_kCbfStopFindActionKeepSelection: CbfStopFindAction = 1;
pub const CbfStopFindAction_kCbfStopFindActionActivateSelection: CbfStopFindAction = 2;
pub type CbfStopFindAction = ::std::os::raw::c_uint;
