macro_rules! for_each_bridge_call {
    ($macro:ident) => {
        $macro!(cbf_bridge_set_base_bundle_id, CbfBridgeSetBaseBundleIdFn, (bundle_id: *const std::os::raw::c_char), (), (bundle_id));
        $macro!(cbf_bridge_client_create, CbfBridgeClientCreateFn, (), *mut CbfBridgeClientHandle, ());
        $macro!(cbf_bridge_client_destroy, CbfBridgeClientDestroyFn, (client: *mut CbfBridgeClientHandle), (), (client));
        $macro!(cbf_bridge_init, CbfBridgeInitFn, (), (), ());
        $macro!(cbf_bridge_prepare_channel, CbfBridgePrepareChannelFn, (out_switch_arg: *mut c_char, out_arg_len: i32), i32, (out_switch_arg, out_arg_len));
        $macro!(cbf_bridge_pass_child_pid, CbfBridgePassChildPidFn, (child_pid: i64), (), (child_pid));
        $macro!(cbf_bridge_client_connect_inherited, CbfBridgeClientConnectInheritedFn, (client: *mut CbfBridgeClientHandle), bool, (client));
        $macro!(cbf_bridge_client_authenticate, CbfBridgeClientAuthenticateFn, (client: *mut CbfBridgeClientHandle, token: *const c_char), bool, (client, token));
        $macro!(cbf_bridge_client_wait_for_event, CbfBridgeClientWaitForEventFn, (client: *mut CbfBridgeClientHandle, timeout_ms: i64), i32, (client, timeout_ms));
        $macro!(cbf_bridge_client_poll_event, CbfBridgeClientPollEventFn, (client: *mut CbfBridgeClientHandle, out_event: *mut CbfBridgeEvent), bool, (client, out_event));
        $macro!(cbf_bridge_event_free, CbfBridgeEventFreeFn, (event: *mut CbfBridgeEvent), (), (event));
        $macro!(cbf_bridge_client_get_profiles, CbfBridgeClientGetProfilesFn, (client: *mut CbfBridgeClientHandle, out_list: *mut CbfProfileList), bool, (client, out_list));
        $macro!(cbf_bridge_profile_list_free, CbfBridgeProfileListFreeFn, (list: *mut CbfProfileList), (), (list));
        $macro!(cbf_bridge_client_list_extensions, CbfBridgeClientListExtensionsFn, (client: *mut CbfBridgeClientHandle, profile_id: *const c_char, out_list: *mut CbfExtensionInfoList), bool, (client, profile_id, out_list));
        $macro!(cbf_bridge_extension_list_free, CbfBridgeExtensionListFreeFn, (list: *mut CbfExtensionInfoList), (), (list));
        $macro!(cbf_bridge_client_create_tab, CbfBridgeClientCreateTabFn, (client: *mut CbfBridgeClientHandle, request_id: u64, initial_url: *const c_char, profile_id: *const c_char), bool, (client, request_id, initial_url, profile_id));
        $macro!(cbf_bridge_client_request_close_tab, CbfBridgeClientRequestCloseTabFn, (client: *mut CbfBridgeClientHandle, tab_id: u64), bool, (client, tab_id));
        $macro!(cbf_bridge_client_set_tab_size, CbfBridgeClientSetTabSizeFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, width: u32, height: u32), bool, (client, tab_id, width, height));
        $macro!(cbf_bridge_client_set_tab_background_policy, CbfBridgeClientSetTabBackgroundPolicyFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, transparent: bool), bool, (client, tab_id, transparent));
        $macro!(cbf_bridge_client_set_extension_popup_size, CbfBridgeClientSetExtensionPopupSizeFn, (client: *mut CbfBridgeClientHandle, popup_id: u64, width: u32, height: u32), bool, (client, popup_id, width, height));
        $macro!(cbf_bridge_client_set_extension_popup_background_policy, CbfBridgeClientSetExtensionPopupBackgroundPolicyFn, (client: *mut CbfBridgeClientHandle, popup_id: u64, transparent: bool), bool, (client, popup_id, transparent));
        $macro!(cbf_bridge_client_set_tab_focus, CbfBridgeClientSetTabFocusFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, focused: bool), bool, (client, tab_id, focused));
        $macro!(cbf_bridge_client_set_tab_visibility, CbfBridgeClientSetTabVisibilityFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, visibility: u8), bool, (client, tab_id, visibility));
        $macro!(cbf_bridge_client_enable_tab_ipc, CbfBridgeClientEnableTabIpcFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, allowed_origins: *const CbfCommandList), bool, (client, tab_id, allowed_origins));
        $macro!(cbf_bridge_client_disable_tab_ipc, CbfBridgeClientDisableTabIpcFn, (client: *mut CbfBridgeClientHandle, tab_id: u64), bool, (client, tab_id));
        $macro!(cbf_bridge_client_post_tab_ipc_message, CbfBridgeClientPostTabIpcMessageFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, channel: *const c_char, message_type: u8, request_id: u64, payload_kind: u8, payload_text: *const c_char, payload_binary: *const u8, payload_binary_len: u32, content_type: *const c_char, error_code: u8), bool, (client, tab_id, channel, message_type, request_id, payload_kind, payload_text, payload_binary, payload_binary_len, content_type, error_code));
        $macro!(cbf_bridge_client_set_extension_popup_focus, CbfBridgeClientSetExtensionPopupFocusFn, (client: *mut CbfBridgeClientHandle, popup_id: u64, focused: bool), bool, (client, popup_id, focused));
        $macro!(cbf_bridge_client_send_key_event, CbfBridgeClientSendKeyEventFn, (client: *mut CbfBridgeClientHandle, event: *const CbfKeyEvent, commands: *const CbfCommandList), bool, (client, event, commands));
        $macro!(cbf_bridge_client_send_extension_popup_key_event, CbfBridgeClientSendExtensionPopupKeyEventFn, (client: *mut CbfBridgeClientHandle, popup_id: u64, event: *const CbfKeyEvent, commands: *const CbfCommandList), bool, (client, popup_id, event, commands));
        $macro!(cbf_bridge_client_send_mouse_event, CbfBridgeClientSendMouseEventFn, (client: *mut CbfBridgeClientHandle, event: *const CbfMouseEvent), bool, (client, event));
        $macro!(cbf_bridge_client_send_extension_popup_mouse_event, CbfBridgeClientSendExtensionPopupMouseEventFn, (client: *mut CbfBridgeClientHandle, popup_id: u64, event: *const CbfMouseEvent), bool, (client, popup_id, event));
        $macro!(cbf_bridge_client_send_mouse_wheel_event, CbfBridgeClientSendMouseWheelEventFn, (client: *mut CbfBridgeClientHandle, event: *const CbfMouseWheelEvent), bool, (client, event));
        $macro!(cbf_bridge_client_send_extension_popup_mouse_wheel_event, CbfBridgeClientSendExtensionPopupMouseWheelEventFn, (client: *mut CbfBridgeClientHandle, popup_id: u64, event: *const CbfMouseWheelEvent), bool, (client, popup_id, event));
        $macro!(cbf_bridge_client_send_drag_update, CbfBridgeClientSendDragUpdateFn, (client: *mut CbfBridgeClientHandle, update: *const CbfDragUpdate), bool, (client, update));
        $macro!(cbf_bridge_client_send_drag_drop, CbfBridgeClientSendDragDropFn, (client: *mut CbfBridgeClientHandle, drop: *const CbfDragDrop), bool, (client, drop));
        $macro!(cbf_bridge_client_send_drag_cancel, CbfBridgeClientSendDragCancelFn, (client: *mut CbfBridgeClientHandle, session_id: u64, tab_id: u64), bool, (client, session_id, tab_id));
        $macro!(cbf_bridge_client_send_external_drag_enter, CbfBridgeClientSendExternalDragEnterFn, (client: *mut CbfBridgeClientHandle, event: *const CbfExternalDragEnter), bool, (client, event));
        $macro!(cbf_bridge_client_send_external_drag_update, CbfBridgeClientSendExternalDragUpdateFn, (client: *mut CbfBridgeClientHandle, event: *const CbfExternalDragUpdate), bool, (client, event));
        $macro!(cbf_bridge_client_send_external_drag_leave, CbfBridgeClientSendExternalDragLeaveFn, (client: *mut CbfBridgeClientHandle, tab_id: u64), bool, (client, tab_id));
        $macro!(cbf_bridge_client_send_external_drag_drop, CbfBridgeClientSendExternalDragDropFn, (client: *mut CbfBridgeClientHandle, event: *const CbfExternalDragDrop), bool, (client, event));
        $macro!(cbf_bridge_convert_nsevent, CbfBridgeConvertNseventFn, (nsevent: *mut std::ffi::c_void, tab_id: u64, out_event: *mut CbfKeyEvent), (), (nsevent, tab_id, out_event));
        $macro!(cbf_bridge_free_converted_key_event, CbfBridgeFreeConvertedKeyEventFn, (event: *mut CbfKeyEvent), (), (event));
        $macro!(cbf_bridge_convert_nsevent_to_mouse_event, CbfBridgeConvertNseventToMouseEventFn, (nsevent: *mut std::ffi::c_void, nsview: *mut std::ffi::c_void, tab_id: u64, pointer_type: u8, unaccelerated_movement: bool, out_event: *mut CbfMouseEvent), (), (nsevent, nsview, tab_id, pointer_type, unaccelerated_movement, out_event));
        $macro!(cbf_bridge_convert_nsevent_to_mouse_wheel_event, CbfBridgeConvertNseventToMouseWheelEventFn, (nsevent: *mut std::ffi::c_void, nsview: *mut std::ffi::c_void, tab_id: u64, out_event: *mut CbfMouseWheelEvent), (), (nsevent, nsview, tab_id, out_event));
        $macro!(cbf_bridge_convert_nspasteboard_to_drag_data, CbfBridgeConvertNspasteboardToDragDataFn, (nspasteboard: *mut std::ffi::c_void, out_data: *mut CbfDragData), (), (nspasteboard, out_data));
        $macro!(cbf_bridge_free_converted_drag_data, CbfBridgeFreeConvertedDragDataFn, (data: *mut CbfDragData), (), (data));
        $macro!(cbf_bridge_client_set_composition, CbfBridgeClientSetCompositionFn, (client: *mut CbfBridgeClientHandle, composition: *const CbfImeComposition), bool, (client, composition));
        $macro!(cbf_bridge_client_set_extension_popup_composition, CbfBridgeClientSetExtensionPopupCompositionFn, (client: *mut CbfBridgeClientHandle, popup_id: u64, composition: *const CbfImeComposition), bool, (client, popup_id, composition));
        $macro!(cbf_bridge_client_commit_text, CbfBridgeClientCommitTextFn, (client: *mut CbfBridgeClientHandle, commit: *const CbfImeCommitText), bool, (client, commit));
        $macro!(cbf_bridge_client_commit_extension_popup_text, CbfBridgeClientCommitExtensionPopupTextFn, (client: *mut CbfBridgeClientHandle, popup_id: u64, commit: *const CbfImeCommitText), bool, (client, popup_id, commit));
        $macro!(cbf_bridge_client_finish_composing_text, CbfBridgeClientFinishComposingTextFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, behavior: u8), bool, (client, tab_id, behavior));
        $macro!(cbf_bridge_client_finish_extension_popup_composing_text, CbfBridgeClientFinishExtensionPopupComposingTextFn, (client: *mut CbfBridgeClientHandle, popup_id: u64, behavior: u8), bool, (client, popup_id, behavior));
        $macro!(cbf_bridge_client_execute_edit_action, CbfBridgeClientExecuteEditActionFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, action: u8), bool, (client, tab_id, action));
        $macro!(cbf_bridge_client_find_in_page, CbfBridgeClientFindInPageFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, request_id: u64, query: *const c_char, forward: bool, match_case: bool, new_session: bool, find_match: bool), bool, (client, tab_id, request_id, query, forward, match_case, new_session, find_match));
        $macro!(cbf_bridge_client_stop_finding, CbfBridgeClientStopFindingFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, action: u8), bool, (client, tab_id, action));
        $macro!(cbf_bridge_client_execute_extension_popup_edit_action, CbfBridgeClientExecuteExtensionPopupEditActionFn, (client: *mut CbfBridgeClientHandle, popup_id: u64, action: u8), bool, (client, popup_id, action));
        $macro!(cbf_bridge_client_execute_context_menu_command, CbfBridgeClientExecuteContextMenuCommandFn, (client: *mut CbfBridgeClientHandle, menu_id: u64, command_id: i32, event_flags: i32), bool, (client, menu_id, command_id, event_flags));
        $macro!(cbf_bridge_client_dismiss_context_menu, CbfBridgeClientDismissContextMenuFn, (client: *mut CbfBridgeClientHandle, menu_id: u64), bool, (client, menu_id));
        $macro!(cbf_bridge_client_accept_choice_menu_selection, CbfBridgeClientAcceptChoiceMenuSelectionFn, (client: *mut CbfBridgeClientHandle, request_id: u64, indices: *const CbfChoiceMenuSelectedIndices), bool, (client, request_id, indices));
        $macro!(cbf_bridge_client_dismiss_choice_menu, CbfBridgeClientDismissChoiceMenuFn, (client: *mut CbfBridgeClientHandle, request_id: u64), bool, (client, request_id));
        $macro!(cbf_bridge_client_confirm_beforeunload, CbfBridgeClientConfirmBeforeunloadFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, request_id: u64, proceed: bool), bool, (client, tab_id, request_id, proceed));
        $macro!(cbf_bridge_client_respond_javascript_dialog, CbfBridgeClientRespondJavascriptDialogFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, request_id: u64, accept: bool, prompt_text: *const c_char), bool, (client, tab_id, request_id, accept, prompt_text));
        $macro!(cbf_bridge_client_respond_extension_popup_javascript_dialog, CbfBridgeClientRespondExtensionPopupJavascriptDialogFn, (client: *mut CbfBridgeClientHandle, popup_id: u64, request_id: u64, accept: bool, prompt_text: *const c_char), bool, (client, popup_id, request_id, accept, prompt_text));
        $macro!(cbf_bridge_client_navigate, CbfBridgeClientNavigateFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, url: *const c_char), bool, (client, tab_id, url));
        $macro!(cbf_bridge_client_go_back, CbfBridgeClientGoBackFn, (client: *mut CbfBridgeClientHandle, tab_id: u64), bool, (client, tab_id));
        $macro!(cbf_bridge_client_go_forward, CbfBridgeClientGoForwardFn, (client: *mut CbfBridgeClientHandle, tab_id: u64), bool, (client, tab_id));
        $macro!(cbf_bridge_client_reload, CbfBridgeClientReloadFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, ignore_cache: bool), bool, (client, tab_id, ignore_cache));
        $macro!(cbf_bridge_client_print_preview, CbfBridgeClientPrintPreviewFn, (client: *mut CbfBridgeClientHandle, tab_id: u64), bool, (client, tab_id));
        $macro!(cbf_bridge_client_activate_extension_action, CbfBridgeClientActivateExtensionActionFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, extension_id: *const c_char), bool, (client, tab_id, extension_id));
        $macro!(cbf_bridge_client_close_extension_popup, CbfBridgeClientCloseExtensionPopupFn, (client: *mut CbfBridgeClientHandle, popup_id: u64), bool, (client, popup_id));
        $macro!(cbf_bridge_client_open_dev_tools, CbfBridgeClientOpenDevToolsFn, (client: *mut CbfBridgeClientHandle, tab_id: u64), bool, (client, tab_id));
        $macro!(cbf_bridge_client_inspect_element, CbfBridgeClientInspectElementFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, x: i32, y: i32), bool, (client, tab_id, x, y));
        $macro!(cbf_bridge_client_get_tab_dom_html, CbfBridgeClientGetTabDomHtmlFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, request_id: u64), bool, (client, tab_id, request_id));
        $macro!(cbf_bridge_client_open_default_prompt_ui, CbfBridgeClientOpenDefaultPromptUiFn, (client: *mut CbfBridgeClientHandle, profile_id: *const c_char, request_id: u64), bool, (client, profile_id, request_id));
        $macro!(cbf_bridge_client_register_custom_scheme_handler, CbfBridgeClientRegisterCustomSchemeHandlerFn, (client: *mut CbfBridgeClientHandle, scheme: *const c_char, host: *const c_char), bool, (client, scheme, host));
        $macro!(cbf_bridge_client_respond_custom_scheme_request, CbfBridgeClientRespondCustomSchemeRequestFn, (client: *mut CbfBridgeClientHandle, request_id: u64, result: u8, mime_type: *const c_char, content_security_policy: *const c_char, access_control_allow_origin: *const c_char, body: *const u8, body_len: u32), bool, (client, request_id, result, mime_type, content_security_policy, access_control_allow_origin, body, body_len));
        $macro!(cbf_bridge_client_respond_prompt_ui, CbfBridgeClientRespondPromptUiFn, (client: *mut CbfBridgeClientHandle, profile_id: *const c_char, request_id: u64, prompt_ui_kind: u8, proceed: bool, report_abuse: bool, destination_path: *const c_char), bool, (client, profile_id, request_id, prompt_ui_kind, proceed, report_abuse, destination_path));
        $macro!(cbf_bridge_client_respond_prompt_ui_for_tab, CbfBridgeClientRespondPromptUiForTabFn, (client: *mut CbfBridgeClientHandle, tab_id: u64, request_id: u64, prompt_ui_kind: u8, proceed: bool, report_abuse: bool, destination_path: *const c_char), bool, (client, tab_id, request_id, prompt_ui_kind, proceed, report_abuse, destination_path));
        $macro!(cbf_bridge_client_pause_download, CbfBridgeClientPauseDownloadFn, (client: *mut CbfBridgeClientHandle, download_id: u64), bool, (client, download_id));
        $macro!(cbf_bridge_client_resume_download, CbfBridgeClientResumeDownloadFn, (client: *mut CbfBridgeClientHandle, download_id: u64), bool, (client, download_id));
        $macro!(cbf_bridge_client_cancel_download, CbfBridgeClientCancelDownloadFn, (client: *mut CbfBridgeClientHandle, download_id: u64), bool, (client, download_id));
        $macro!(cbf_bridge_client_close_prompt_ui, CbfBridgeClientClosePromptUiFn, (client: *mut CbfBridgeClientHandle, profile_id: *const c_char, prompt_ui_id: u64), bool, (client, profile_id, prompt_ui_id));
        $macro!(cbf_bridge_client_respond_tab_open, CbfBridgeClientRespondTabOpenFn, (client: *mut CbfBridgeClientHandle, request_id: u64, response_kind: u8, target_tab_id: u64, activate: bool), bool, (client, request_id, response_kind, target_tab_id, activate));
        $macro!(cbf_bridge_client_shutdown, CbfBridgeClientShutdownFn, (client: *mut CbfBridgeClientHandle), (), (client));
        $macro!(cbf_bridge_client_request_shutdown, CbfBridgeClientRequestShutdownFn, (client: *mut CbfBridgeClientHandle, request_id: u64), bool, (client, request_id));
        $macro!(cbf_bridge_client_confirm_shutdown, CbfBridgeClientConfirmShutdownFn, (client: *mut CbfBridgeClientHandle, request_id: u64, proceed: bool), bool, (client, request_id, proceed));
        $macro!(cbf_bridge_client_force_shutdown, CbfBridgeClientForceShutdownFn, (client: *mut CbfBridgeClientHandle), bool, (client));
    };
}

pub(crate) use for_each_bridge_call;
