[book]
authors = ["CBF contributors"]
language = "en"
src = "docs/"
title = "CBF Documentation"

[output.html]
git-repository-url = "https://github.com/tasuren/cbf"
edit-url-template = "https://github.com/tasuren/cbf/edit/main/{path}"

[build]
build-dir = "target/mdbook"
create-missing = false
